molecule: use user-provided IDs in molecule files
lammps/lammps pull request #2450
Opened 2020-10-24 17:09 UTC by jrgissing

**Summary**

previously, the atom IDs in per-atom sections of molecule templates were ignored. though documented, this is rather unintuitive behavior. thanks to Ben Jensen for pointing this out

**Related Issue(s)**

another open PR modifying molecule.* files: #2447 

**Author(s)**

JG

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2020-11-11 17:06 UTC, rbberger requested changes

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Coords section in molecule file");
There should be range check for `iatom < 0` too.

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Types section in molecule file");
Same here.

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Molecules section in molecule file");
Same here.

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Charges section in molecule file");
Same here.

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Diameters section in molecule file");
Same here.

2020-11-11 17:06 UTC, rbberger commented on src/molecule.cpp
> +      if (iatom >= natoms) error->one(FLERR,"Invalid Diameters section in molecule file");
Same here.

2020-11-12 15:22 UTC, rbberger approved these changes

2020-11-12 15:23 UTC, rbberger commented
@sjplimp Please take a look at this one.

2020-11-13 21:27 UTC, sjplimp commented
@jrgissing Not clear on what is being changed or why.  In particular, the doc page was clear (to me)
before, but now it is less clear.  Are you saying with this change the N lines in any per-atom section no longer have to be in order, but presuambly they still need to be complete (N different IDs from 1 to N)?  Also, for the Bonds, Angles, etc sections which list 2 or more atom IDs ?  Those IDs will now match the atom ID (if the atoms are not listed in order), otherwise same as before?  If that is correct, it should be documented more clearly.  Also, I'm not sure it is a good idea to allow users to list atom IDs (or diameters, etc) in some order other than 1 to N.  Is there a motivation for that?  Otherwise the code could verify that the IDs are in order from 1 to N, and thus complete, which with this change would require non-trivial work.

2020-11-14 01:05 UTC, jrgissing commented
> @jrgissing Not clear on what is being changed or why. 
Now that template atom IDs may be referenced, it was unexpected for them to be ignored (specifically, in the context of bond/react). 

> In particular, the doc page was clear (to me) before, but now it is less clear. Are you saying with this change the N lines in any per-atom section no longer have to be in order, but presuambly they still need to be complete (N different IDs from 1 to N)? 
Yes.

> Also, for the Bonds, Angles, etc sections which list 2 or more atom IDs ? Those IDs will now match the atom ID (if the atoms are not listed in order), otherwise same as before?
Yes.

> If that is correct, it should be documented more clearly. Also, I'm not sure it is a good idea to allow users to list atom IDs (or diameters, etc) in some order other than 1 to N. Is there a motivation for that? Otherwise the code could verify that the IDs are in order from 1 to N, and thus complete, which with this change would require non-trivial work.
I think the out-of-order issue comes up when molecule templates are created from data files, which don't always keep atom order. I can add a completeness check.

2020-11-14 21:01 UTC, jrgissing commented
ok, the completeness check has been added. also eliminates some confusing variable shadowing

2020-11-16 15:46 UTC, sjplimp commented
@jrgissing ok - your comments above and code changes look fine.  My only last comment is that the change to the doc page molecule.rst now seems incorrect?  Should it say the lines in per-atom sections need to include a setting for every atom (IDs for 1 to Natoms) but the lines can be in any order?

2020-11-18 21:01 UTC, rbberger commented
@sjplimp please approve for merge

2020-11-18 21:26 UTC, sjplimp approved these changes

2020-11-18 22:52 UTC, merged