Temperature-grouped Nose-Hoover thermostat for Drude polarizable model
lammps/lammps pull request #2483
Opened 2020-11-16 20:15 UTC by z-gong

**Summary**

Two fix styles _tgnvt/drude_ and _tgnpt/drude_ are added, which enable Nose-Hoover integration with the temperature-grouped Nose-Hoover (TGNH) thermostat for Drude polarizable model.

In thermolized Drude simulation, conventional dual-temperature thermostat schemes often suffer from violations of equipartitioning, leading to considerable errors in both static and dynamic properties. Heat flow from the real degrees of freedom to the Drude degrees of freedom leads to a steady temperature gradient and puts the system at an incorrect effective temperature. Systems with high-frequency internal degrees of freedom such as planar improper dihedrals or C–H bond stretches are most vulnerable.

This new thermostat assigns the molecular center of mass translations to a temperature group separated from the rest degrees of freedom, therefore giving better description for static and dynamic properties.

**Related Issue(s)**

None

**Author(s)**

Zheng Gong, ENS de Lyon, z.gong@outlook.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

None

**Implementation Notes**

As described in the paper "Proper Thermal Equilibration of Simulations with Drude Polarizable Models: Temperature-Grouped Dual-Nosé–Hoover Thermostat", TGNH separates the kinetic energy of the system into three contributions: molecular center of mass (COM) motion, motion of COM of atom-Drude pairs or non-polarizable atoms relative to molecular COM, and relative motion of atom-Drude pairs. An independent Nose-Hoover chain is applied to each type of motion.

The correctness is verified by inspecting the temperatures of those three types of motions and comparing the calculated density and viscosity with the results of SCF approach in GROMACS.

No other feature in LAMMPS is affected.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

Paper describing the thermostat
https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.9b02983

2020-11-17 00:31 UTC, rbberger requested changes
Looks like your code fails to compile for `LAMMPS_BIGBIG`. Some variables need to be declared as `tagint` instead of `int`.

See https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fcentos7%2Fcmake_mpi_openmp_bigbig_static/detail/cmake_mpi_openmp_bigbig_static/1670/pipeline

2020-11-18 16:36 UTC, z-gong commented
> 
> Looks like your code fails to compile for `LAMMPS_BIGBIG`. Some variables need to be declared as `tagint` instead of `int`.
> 

Thanks. I have fixed this issue.

2020-12-23 15:31 UTC, sjplimp approved these changes

2020-12-23 16:35 UTC, rbberger approved these changes

2020-12-23 16:39 UTC, merged