Refactor MEAMC potential reader
lammps/lammps pull request #2657
Opened 2021-03-12 20:56 UTC by rbberger

**Summary**

Refactor MEAMC potential reader code to use `PotentialFileReader`

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2021-03-13 18:55 UTC, martok requested changes
Code-based review without having compiled it since I'm away from my dev box... trusting the regtests for now.

I found two type confusions, the rest looks good to me. It's pretty amazing how much nicer modern C++ can look compared to the mostly-C-ish baseline.

2021-03-13 18:55 UTC, martok commented on src/USER-MEAMC/meam.h
>  #include <cstring>
IWYU: with str_to_lat updated, there is nothing using functions from cstring left in the header.

2021-03-13 18:55 UTC, martok commented on src/USER-MEAMC/pair_meamc.cpp
> +        ibar[index] = values.next_double();
ibar is int -> values.next_int()

2021-03-13 18:55 UTC, martok commented on src/USER-MEAMC/pair_meamc.cpp
> +        ielement[index] = values.next_double();
ielement is int -> values.next_int()

2021-03-13 18:55 UTC, martok commented on src/USER-MEAMC/pair_meamc.cpp
> +    ValueTokenizer values(line, "=(), '\t\n\r\f");
Damn, I had completely forgotten how hacky this namelist "parsing" was...
(just a random thought, it's fine for this PR)

2021-03-15 00:49 UTC, rbberger commented
@martok Good catches :smile:

2021-03-15 08:45 UTC, martok approved these changes

2021-03-16 03:13 UTC, akohlmey approved these changes

2021-03-16 19:32 UTC, sjplimp approved these changes

2021-03-16 21:14 UTC, merged