Improvement of the SPIN package by removing a limitation
lammps/lammps pull request #2714
Opened 2021-04-19 23:39 UTC by julient31

**Summary**

This PR:
- corrected a limitation of the SPIN package: only one fix precession/spin or langevin/spin could be declared for each simulation. This is no longer the case.
- implemented a spin-transfer torque in fix precession/spin
- improved the test_problem setup

**Related Issue(s)**

None.

**Author(s)**

Julien Tranchida (Sandia National Labs), julien.tranchida1@gmail.com
Theophile Chirac (CEA, helped with the implementation of the spin-transfer torque), theophile.chirac@cea.fr

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes: all former input scripts will still be fully valid.

**Implementation Notes**

All validation tests of the SPIN package were successfully passed. This is important as changes were made in fix nve/spin, langevin/spin and precession/spin. 

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

2021-04-20 23:52 UTC, akohlmey requested changes
@julient31 I have some suggestion for cosmetic changes, a couple of cases where upstream changes were accidentally reverted, and flagged some possible division by zero issues that should be checked for after parsing the input arguments.

2021-04-20 23:52 UTC, akohlmey commented on src/SPIN/fix_langevin_spin.cpp
> +#include "compute.h"
I don't see where compute.h would need to be included here.

2021-04-20 23:52 UTC, akohlmey commented on src/SPIN/fix_precession_spin.cpp
> +    inorm = 1.0/sqrt(nsttx*nsttx + nstty*nstty + nsttz*nsttz);
There doesn't seem to be a check whether nsttx, netty and nsttz are valid input. from the context it seems they should be > 1. They most certainly must not be all 0 or else there would be a division by zero error here.

2021-04-20 23:52 UTC, akohlmey commented on src/SPIN/fix_precession_spin.cpp
> +    inorm = 1.0/sqrt(n6x*n6x + n6y*n6y + n6z*n6z);
same issue about division by zero from before.

2021-04-20 23:52 UTC, akohlmey commented on src/SPIN/fix_precession_spin.cpp
> -  if (utils::strmatch(update->integrate_style,"^respa")) {
this change should be reverted.

2021-04-20 23:52 UTC, akohlmey commented on src/SPIN/fix_precession_spin.cpp
> +  if (strstr(update->integrate_style,"verlet"))
this change should be reverted

2021-04-21 16:57 UTC, julient31 commented
Hey @akohlmey and @sjplimp 

Thanks so much for the reviews! I think I corrected everything. Let me know if you need me to modify something else!

Best,
Julien.

2021-04-21 18:54 UTC, akohlmey approved these changes

2021-04-21 18:55 UTC, merged