Updates to the Programmer guide section of the manual
lammps/lammps pull request #2917
Opened 2021-09-01 16:33 UTC by akohlmey

**Summary**

This reviews and updates parts of the manual for the upcoming stable release. It updates the programmer guide section about submitting contributions and integrates the draft guidelines from issue #2643. I also integrates some discussions and explanations of core algorithms that are adapted from the new LAMMPS paper. Where meaningful, relevant functions in the C++ API are decorated with doxygen style comments and included into the manual.

**Related Issue(s)**

#2643 

**Author(s)**

Axel Kohlmeyer, Temple U, plus the authors of the LAMMPS paper.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system

2021-09-23 12:15 UTC, akohlmey commented
@sjplimp @athomps @stanmoore1 @rbberger
Since the new LAMMPS paper is now accepted, has been assigned a DOI, and the "pre-proof version" has been posted online at https://doi.org/10.1016/j.cpc.2021.108171, we should consider including this pull request into the stable version and also update the information about citing LAMMPS accordingly. Even though we cannot provide the exact reference until later, we can include the DOI link which will point to the correct citation as soon as it is available and we can update the text in the manual and the website then as well. Since a large number of people will be using the stable version, I think it would be beneficial to get this included.
At the very least the reference to the new paper.

2021-09-23 15:01 UTC, athomps commented
Sounds good to me.

2021-09-23 15:04 UTC, sjplimp commented
Including DOI is fine.  As I mentioned before, if this content is going into the programmer guide, it needs to clearly say this content, esp the figures, is from the paper.

2021-09-23 16:01 UTC, akohlmey commented
> Including DOI is fine. As I mentioned before, if this content is going into the programmer guide, it needs to clearly say this content, esp the figures, is from the paper.

Made some changes to do that. Please check it out. If it is not clear enough, please suggest how to improve.

2021-09-23 16:58 UTC, sjplimp commented on doc/src/Intro_citing.rst
> +The original publication describing LAMMPS in its early implementations is:
The original pub describing the parallel algorithms used in the initial versions of LAMMPS is:

2021-09-23 17:00 UTC, sjplimp commented on doc/src/Intro_citing.rst
> +describing the core of LAMMPS, but then also publications describing the
but also pubs describing particular models or algorithms implemented in LAMMPS

2021-09-23 17:01 UTC, sjplimp commented on doc/src/Intro_citing.rst
> +So any project using LAMMPS or a derivative application that uses LAMMPS
So a project ...

2021-09-23 17:03 UTC, sjplimp commented on doc/src/Intro_citing.rst
> +The canonical publication that describes the basic features, the source
The latest canonical ...

2021-09-23 17:05 UTC, sjplimp commented on doc/src/Developer_parallel.rst
> +LAMMPS is from ground up designed to be running in parallel using the
LAMMPS is designed to enable running in parallel ...

2021-09-23 17:10 UTC, sjplimp requested changes

2021-09-23 17:10 UTC, sjplimp commented on doc/src/Developer_parallel.rst
> +parallelization has to be efficient to enable good strong scaling (=
... parallelization aims to be efficient so as to enable ...

2021-09-23 17:10 UTC, sjplimp commented on doc/src/Developer_parallel.rst
> +size).  Additional parallelization using GPUs or OpenMP can then be
can also be applied

2021-09-23 17:10 UTC, sjplimp commented on doc/src/Developer_parallel.rst
> +   The text and most of the figures in this chapter were adapted
thanks

2021-09-23 18:58 UTC, athomps approved these changes
I approve

2021-09-23 20:06 UTC, akohlmey commented
@sjplimp it looks like we also need to update the links to the original JCP paper on your home page. When I try to follow them I get an error about "too many redirects".

2021-09-24 14:39 UTC, sjplimp approved these changes

2021-09-24 15:27 UTC, merged