Fix issues in compute ave/sphere/atom
lammps/lammps pull request #3293
Opened 2022-06-06 22:17 UTC by stanmoore1

**Summary**

- Add neglected unit conversions
- Take into account 2D vs 3D
- Use mass instead of number density

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

2022-06-09 21:52 UTC, stanmoore1 commented
@sjplimp ready for review

2022-06-09 22:03 UTC, sjplimp requested changes

2022-06-09 22:03 UTC, sjplimp commented on doc/src/compute_ave_sphere_atom.rst
> +for each atom and neighbors inside a spherical cutoff. The center-of-mass
its neighbors

2022-06-10 14:31 UTC, sjplimp commented
@stanmoore1 I expanded the first paragraph of the description to give more details as to how the 2 quantities are calculated for each atom.

2022-06-10 15:05 UTC, stanmoore1 commented
@sjplimp looks great, thanks! @akohlmey I think this is ready to merge.

2022-06-10 16:43 UTC, sjplimp approved these changes

2022-06-10 16:57 UTC, merged