Add pair_modify option to allow separate cutoffs for each neigh list …
lammps/lammps pull request #3341
Opened 2022-07-07 22:55 UTC by stanmoore1

…with pair hybrid/overlay

**Summary**

This PR adds a `pair_modify` option: `neigh/trim` to allow separate cutoffs for each neigh list with `pair hybrid/overlay` and also adds "trim" methods for building a neighbor list with a shorter cutoff from one with a longer cutoff. This can give speedup when the cutoffs are significantly different.

For example, consider the following input command:

```
pair_style      hybrid/overlay lj/cut 2.5 coul/cut 5.0
pair_coeff      1 1 lj/cut 1.0 1.0
pair_coeff      1 1 coul/cut
```

With `pair_modify neigh/trim no` the code gives the same behavior as before:

```
  master list distance cutoff = 5.3
  ghost atom cutoff = 5.3
  binsize = 2.65, bins = 13 13 13
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair lj/cut, perpetual
      attributes: half, newton on
      pair build: half/bin/atomonly/newton
      stencil: half/bin/3d
      bin: standard
  (2) pair coul/cut, perpetual, copy from (1)
      attributes: half, newton on
      pair build: copy
      stencil: none
      bin: none
```

While with `pair_modify neigh/trim yes` the code builds a separate neigh list for `lj/cut` by trimming the neigh list built for `coul/cut`:

```
  master list distance cutoff = 5.3
  ghost atom cutoff = 5.3
  binsize = 2.65, bins = 13 13 13
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair lj/cut, perpetual, trim from (2)
      attributes: half, newton on, cut 2.8
      pair build: trim
      stencil: none
      bin: none
  (2) pair coul/cut, perpetual
      attributes: half, newton on
      pair build: half/bin/atomonly/newton
      stencil: half/bin/3d
      bin: standard
```

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL), with helpful discussions from Steve Plimpton (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2022-07-08 08:06 UTC, akohlmey commented
FYI, there are three segmentation faults for unit tests. This often happens when there is some uninitialized data.

2022-07-11 15:45 UTC, stanmoore1 commented
This is working in all my tests. One question, should `neigh/trim yes` be the default since it is normally faster, or should we keep the old behavior? @sjplimp @akohlmey

2022-07-11 16:25 UTC, athomps approved these changes
I approve.

2022-07-11 18:46 UTC, akohlmey commented
> This is working in all my tests. One question, should `neigh/trim yes` be the default since it is normally faster, or should we keep the old behavior? @sjplimp @akohlmey 

There still seem to be test failures with the embedded unit tests. I will need some time to reconfigure my phone to find a provider that supports roaming and the wifi hotspot of my cell phone before I can check it out in detail.

If we find and resolve the causes of the failures, I would suggest to make the new option the default. We are at the beginning of a development cycle and now is the best time for such changes and this way we increase the chances of getting bug reports.
If it turns out to be too risky, we can always roll it back and put a warning into the manual (faster but may not work for all cases).

2022-07-12 03:47 UTC, akohlmey requested changes
There are many failed unit tests now:
https://ci.lammps.org/view/LAMMPS%20develop/job/dev/job/pull_requests/job/ubuntu/job/unit_tests/job/cmake_mpi_openmp_smallbig_shared/5027/

2022-07-12 04:18 UTC, akohlmey commented
@stanmoore1 I fixed two bugs, one due to an uninitialized variable and one in pair style hybrid/scaled due to an unallocated array (that style overrides the settings() functions from pair style hybrid).

2022-07-12 07:05 UTC, akohlmey approved these changes

2022-07-12 07:06 UTC, akohlmey commented
With the last two commits all unit tests pass.

2022-07-12 07:42 UTC, akohlmey commented
There are still issues running with OpenMP, e.g. the command `~/compile/lammps/build-test/lmp -in in.snap.InP.JCPA2020 -sf omp` in the examples/snap folder yields:
```
Hybrid pair style last /omp style zbl
Last active /omp style is pair_style zbl
ERROR: Requested neighbor pair method does not exist (src/neighbor.cpp:928)
Last command: run             ${nsteps}
```
Please see: https://ci.lammps.org/job/dev/job/pull_requests/job/ubuntu/job/run_tests/job/cmake_testing_openmp/563/
There may be similar issues when using the INTEL package as well.

2022-07-12 07:45 UTC, akohlmey requested changes
The listed failing inputs need to be able to run without error.

2022-07-12 13:50 UTC, stanmoore1 commented
@akohlmey thanks for working on this--I will fix the OMP/INTEL issue

2022-07-12 14:29 UTC, akohlmey commented
@stanmoore1 wouldn't it be cleaner to just define "forwarders" to the non-accelerated version like for the "skip" neighbor list classes in `src/OPENMP/npair_skip_omp.h`?

2022-07-12 14:30 UTC, stanmoore1 commented
Yes, I didn't know that was an option.

2022-07-12 14:32 UTC, akohlmey commented
> Yes, I didn't know that was an option.

...and I didn't think of it until I saw your commit. :disappointed:

2022-07-12 14:33 UTC, stanmoore1 commented
I don't think that will work for INTEL though, since the structure of the neigh list is different?

2022-07-12 14:40 UTC, akohlmey commented
> I don't think that will work for INTEL though, since the structure of the neigh list is different?

I don't know. Haven't looked at those in a long time. That would be a question for @wmbrownIntel

2022-07-12 16:00 UTC, stanmoore1 commented
@akohlmey it was fairly trivial to add `npair trim` methods for OPENMP and INTEL. If you could test the new code that would be helpful. Thanks

2022-07-12 16:14 UTC, stanmoore1 commented
@akohlmey there may be other corner cases that would error out, i.e. `trim + ssa` or `trim + respa`, any ideas what to do about that?

2022-07-12 16:23 UTC, stanmoore1 commented
One other issue I noticed is that this code in `pair_hybrid` doesn't work if a pair_style has multiple neigh list requests (e.g. MEAM): https://github.com/lammps/lammps/blob/develop/src/pair_hybrid.cpp#L622, since it just finds the first request and then breaks out.

2022-07-12 19:06 UTC, stanmoore1 commented
The Intel trim is broken in my test, debugging...

2022-07-12 20:38 UTC, stanmoore1 commented
@akohlmey this is now passing my tests. Besides the issue of `pair_hybrid` not handling a pair_style that has multiple neigh list requests, this is ready to merge from my POV.

2022-07-12 23:26 UTC, akohlmey commented
> One other issue I noticed is that this code in `pair_hybrid` doesn't work if a pair_style has multiple neigh list requests (e.g. MEAM): https://github.com/lammps/lammps/blob/develop/src/pair_hybrid.cpp#L622, since it just finds the first request and then breaks out.
> 

This sounds like a job for @sjplimp to look into, and it may be a more general problem that could be reported as a separate issue and then addressed in a separate pull request.

2022-07-12 23:31 UTC, akohlmey approved these changes

2022-07-13 14:51 UTC, merged