Improve errors
lammps/lammps pull request #3394
Opened 2022-08-12 11:28 UTC by crackboy88

**Summary**
I have improved some error messages in minimize.cpp and neighbor.cpp.

**Related Issue(s)**

**Author(s)**
Jiancheng Chen

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2022-08-12 15:08 UTC, akohlmey requested changes
@crackboy88 thank your very much for your submission and for being the first Code Clinic participant to do so. :+1: 

I've added some comments. Specifically to individual lines, but keep in mind that in some cases the same issue is repeated multiple times and thus should be addressed multiple times.

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +      if (iarg+2 > narg) error->all(FLERR, "Invalid every keyword: expected 1 every argument");
Unlike what we discussed with the `narg !=` test case. This is a case where you *should* be using `utils::missing_cmd_args()`.

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +      if (every <= 0) error->all(FLERR, "Invalid every argument: {}", every);
This should be "Invalid neigh_modify every argument: {}"
Same for multiple cases below

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +      if (includegroup == -1)
Please don't change the logic. `includegroup < 0` is more defensive programming (and won't make a difference in practice).

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +      if (iarg+2 > narg) error->all(FLERR, "Invalid exclude keyword: loss exclude arguments");
I don't know what this message means, but see my previous comment about using `utils::missing_cmd_args()` for all these cases where arguments are missing.

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +      } else error->all(FLERR,"Invalid exclude keyword: {} argument doesn't exist", arg[iarg+1]);
Better to write here: "Unknown neigh_modify exclude keyword: {}"

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +    } else error->all(FLERR,"Illegal neigh_modify command: {} keyword doesn't exist", arg[iarg]);
See similar comment about: This would better be "Unknown neigh_modify keyword: {}"

2022-08-12 15:08 UTC, akohlmey commented on src/neighbor.cpp
> +}
Please make certain that there is a newline character at the end of the file (check your editor settings, if necessary).

2022-08-13 01:49 UTC, akohlmey approved these changes

2022-08-15 15:21 UTC, athomps approved these changes
Looks great!

2022-08-15 19:47 UTC, merged