Update contact email address in LAMMPS sources
lammps/lammps pull request #3495
Opened 2022-10-21 00:46 UTC by akohlmey

**Summary**

This changes the contact email address in the LAMMPS sources to devlopers@lammps.org
Also the tool for checking the LAMMPS homepage URL was extended to check for compliance and optionally fix sources.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This only changes comments, so there should be no issues.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

2022-10-21 02:37 UTC, stanmoore1 reviewed
I approve

2022-10-21 17:09 UTC, stanmoore1 approved these changes

2022-10-24 13:54 UTC, sjplimp commented on examples/COUPLE/fortran/libfwrapper.c
> +   The LAMMPS Developers, developers@lammps.org
i'd prefer this line be like this everywhere:
LAMMPS development team: developers@lammps.org

2022-10-24 13:54 UTC, sjplimp requested changes
Hoping this tag line is easy to change

2022-10-24 15:10 UTC, akohlmey commented on examples/COUPLE/fortran/libfwrapper.c
> +   The LAMMPS Developers, developers@lammps.org
done

2022-10-24 17:20 UTC, sjplimp approved these changes

2022-10-24 17:49 UTC, merged