Fortran2 updates
lammps/lammps pull request #3572
Opened 2022-12-23 02:36 UTC by hammondkd

**Summary**

Added obsolescence warnings to examples/COUPLE/fortran2 in light of the changes to fortran/lammps.f90.

**Author(s)**

@hammondkd
Karl Hammond
University of Missouri

**Licensing**

By submitting this pull request, I agree that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This does not change anything other than comments, but it warns users that future changes may remove this directory.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

2022-12-23 03:09 UTC, akohlmey commented
@hammondkd just added one fix for a bug that I came across earlier today.

There is another issue with the code here: https://github.com/hammondkd/lammps/blob/885108e95ba18415d6ad3939ccead15a596bce69/fortran/lammps.f90#L2813

```
/home/akohlmey/compile/lammps/fortran/lammps.f90:2813:30:

 2813 |         ext_data = [ext_data, fix_external_data()] ! extends ext_data by 1
      |                              1
Error: Fortran 2008: No initializer for allocatable component ‘id’ given in the structure constructor at (1)
make[2]: *** [unittest/fortran/CMakeFiles/flammps.dir/build.make:75: unittest/fortran/CMakeFiles/flammps.dir/home/akohlmey/compile/lammps/fortran/lammps.f90.o] Error 1
```

This is only triggered when compiling testing with full optimization (which is not a good idea most of the time), so it went unnoticed for a while and I am stuck with a bunch of non-Fortran stuff right now...

2022-12-23 04:13 UTC, hammondkd commented
> There is another issue with the code here: https://github.com/hammondkd/lammps/blob/885108e95ba18415d6ad3939ccead15a596bce69/fortran/lammps.f90#L2813
> 
> ```
> /home/akohlmey/compile/lammps/fortran/lammps.f90:2813:30:
> 
>  2813 |         ext_data = [ext_data, fix_external_data()] ! extends ext_data by 1
>       |                              1
> Error: Fortran 2008: No initializer for allocatable component ‘id’ given in the structure constructor at (1)
> make[2]: *** [unittest/fortran/CMakeFiles/flammps.dir/build.make:75: unittest/fortran/CMakeFiles/flammps.dir/home/akohlmey/compile/lammps/fortran/lammps.f90.o] Error 1
> ```
> 
> This is only triggered when compiling testing with full optimization (which is not a good idea most of the time), so it went unnoticed for a while and I am stuck with a bunch of non-Fortran stuff right now...

I think I fixed this by creating a constructor that explicitly assigns the allocatable string. The issue was with the Fortran 2003 standard; using -std=f2008 eliminated the warning, which is probably why we didn't see it before.

2022-12-23 04:49 UTC, akohlmey commented
> I think I fixed this by creating a constructor that explicitly assigns the allocatable string. The issue was with the Fortran 2003 standard; using -std=f2008 eliminated the warning, which is probably why we didn't see it before.

Thanks. I hope to find some time in the next couple of weeks to revisit the library interface and write more examples and tests and check out the details.

2022-12-23 12:02 UTC, akohlmey commented
While looking through the COUPLE examples folder I noticed that it is time to remove the legacy Fortran 77 wrapper and make a few more updates to README and manual files.

2022-12-24 00:28 UTC, stanmoore1 requested changes

2022-12-24 00:28 UTC, stanmoore1 commented on doc/src/Fortran.rst
> +would need to b imported by the Fortran code that uses the interface.  A
typo: b --> be

2022-12-25 04:12 UTC, akohlmey approved these changes

2023-01-03 18:53 UTC, stanmoore1 approved these changes

2023-01-03 20:04 UTC, merged