Bond/react updates+tests
lammps/lammps pull request #3648
Opened 2023-02-12 05:51 UTC by jrgissing

**Summary**

1) fixes a bug (seg fault) when choosing between overlapping reaction sites when there were more than two overlapping sites near a processor boundary 

2) fixes a bug (seg fault) when reading restart files for bond/react (recently introduced with 'rate_limit' keyword)

3) adds a simple unit test for bond/react

adds a simple unit test

**Related Issue(s)**

none

**Author(s)**

JG

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2023-02-21 17:16 UTC, akohlmey requested changes
@jrgissing while I appreciate your attempt at implementing tests for your fix, I don't think that adding this to the timestep fix tester is a good idea. It would be much more suitable to write a standalone tester program that can then apply a wide variety of tests that are specific to the fix and systematically check out all available functionality.

2023-02-21 17:57 UTC, jrgissing commented
okay, that makes more sense. I will revert commits related to the unit test

2023-03-01 22:53 UTC, stanmoore1 approved these changes
I approve

2023-03-02 02:01 UTC, akohlmey approved these changes

2023-03-02 02:01 UTC, merged