use of type labels in set commands for atom
lammps/lammps pull request #3698
Opened 2023-03-22 14:03 UTC by yafshar

**Summary**

This PR enables the use of type labels in set commands for atom.

```bash
labelmap atom 1 C 8 H
set atom C charge 1.0
set atom H charge -1.0
```

**Related Issue(s)**

**Author(s)**

Yaser Afshar

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2023-03-23 15:02 UTC, sjplimp commented
@yafshar Sorry, there are a few things about this PR I don't understand.

(1) I thought the only use for type labels in an input script was to replace an atom type (in this case for the set command) with a type label.  But you are proposing to replace atom IDs with a type label?  Shouldn't the supported command be:
set type C charge 1.0 ?  Assuming you want to change all C atoms.  Which would alter the TYPE_SELECT portion of selection(), not ATOM_SELECT.

(2) I don't understand how the code you've added to the ATOM_SELECT portion works.  Does utils::expand_type() return a numeric type as a string?  E.g. C --> 3 ?  You can't compare atom tags (IDs) to an atom type.  What does your test script do?

(3) If the functionality of the set command is enhanced, it has to be documented on the doc/src/set.rst file.  And probably other places where type labels are discussed in the doc pages. Those changes need to be in this PR.

Finally, you should add @jrgissing Jake Gissinger to the review list for this PR.

2023-03-23 15:41 UTC, yafshar commented
> (1) I thought the only use for type labels in an input script was to replace an atom type (in this case for the set command) with a type label. But you are proposing to replace atom IDs with a type label? Shouldn't the supported command be: set type C charge 1.0 ? Assuming you want to change all C atoms. Which would alter the TYPE_SELECT portion of selection(), not ATOM_SELECT.

No, it was not the only use case. When we did the type labels with Jake, we thought many places in LAMMPS could take advantage of type labels, but we should enhance the code step by step per users' requests or need. We already did the same for [mass command](https://docs.lammps.org/mass.html). Now I am enhancing the kim in LAMMPS for bonded force fields, and we need to use type labels for the charge there. 
In my view, ATOM_SELECT was the natural case to add this change. Because users naturally use labels for atoms, but I see your point, we can add the same enhancement to TYPE_SELECT  as well.
> 
> (2) I don't understand how the code you've added to the ATOM_SELECT portion works. Does utils::expand_type() return a numeric type as a string? E.g. C --> 3 ? You can't compare atom tags (IDs) to an atom type. What does your test script do?
> 

@akohlmey  wrote [expand_type](utils::expand_type()) utility to do extra checks on the label, which expand the type label string into its equivalent numeric type and returns a null pointer if the type label is not defined.

> (3) If the functionality of the set command is enhanced, it has to be documented on the doc/src/set.rst file. And probably other places where type labels are discussed in the doc pages. Those changes need to be in this PR.
> 
I will complete the command and add the proper document.

> Finally, you should add @jrgissing Jake Gissinger to the review list for this PR.
done!

2023-03-23 15:49 UTC, sjplimp commented
@yafshar I don't think you are understanding my (2) comment.  I do not see how comparing a atom type to atom IDs 
can possibly work to select atoms, which is what the login in ATOM_SELECT is doing.  Am I mis-understanding something ?

Also, re (1), I am not saying type labels cannot be used internally within LAMMPS in creative ways (e.g. fix bond/react, KIM).
I am saying I don't think there is any use case for them in an input script (or data./molecule file) other than to replace a numeric type (atom, bond, etc).  That is why in the set command, you have to add support for a type label only to replace a numeric atom type.  Same as for the mass command.

2023-03-23 15:53 UTC, yafshar commented
> @yafshar I don't think you are understanding my (2) comment. I do not see how comparing a atom type to atom IDs can possibly work to select atoms, which is what the login in ATOM_SELECT is doing. Am I mis-understanding something ?
Thanks, @sjplimp, I got your point. You are right. I will modify the code to account for TYPE_SELECT, which makes more sense.

> Also, re (1), I am not saying type labels cannot be used internally within LAMMPS in creative ways (e.g. fix bond/react, KIM). I am saying I don't think there is any use case for them in an input script (or data./molecule file) other than to replace a numeric type (atom, bond, etc). That is why in the set command, you have to add support for a type label only to replace a numeric atom type. Same as for the mass command.
Agreed. I will modify the PR, later today.

2023-03-24 14:08 UTC, yafshar commented
@jrgissing, would you please check this PR, and update the doc if you see a need?

2023-03-24 15:32 UTC, akohlmey commented
@yafshar can you please complete and insert the following paragraph into the set command documentation:

```
.. versionchanged:: TBD

   Support for type labels was added for 

```

At line 186 before "The style *atom*" and the same at line 243 before "Keyword *type*".

TBD will be updated when the next release is made and then people reading the online documentation that use older versions of LAMMPS can see why their input fails if they try to use type labels.

2023-03-25 14:35 UTC, akohlmey commented
@yafshar You inserted the tags, but didn't complete them. So I did this now. Please check for correctness.
Also, please note that you introduced memory leaks, since the result for `utils::expand_type()` is a temporary string that must be freed with `delete[]`.

2023-03-25 14:36 UTC, akohlmey commented
@sjplimp This now looks OK to me.

2023-03-25 15:21 UTC, yafshar commented
> @yafshar You inserted the tags, but didn't complete them. So I did this now. Please check for correctness. Also, please note that you introduced memory leaks, since the result for `utils::expand_type()` is a temporary string that must be freed with `delete[]`.

Thanks, @akohlmey

2023-03-27 14:33 UTC, jrgissing requested changes

2023-03-27 14:33 UTC, jrgissing commented on doc/src/set.rst
> +Keyword *type/fraction* sets the atom type or atom type label for a fraction
You don't need to add "or atom type label" here. The command does not set the atom type label, it still just sets the atom type. This PR simply allows type labels to set the atom type.

2023-03-27 14:33 UTC, jrgissing commented on doc/src/set.rst
> +style *type* selects all the atoms in a range of types or type labels.
Adding "or type labels" here is somewhat redundant, as stated. Atoms are still just selected by type, this PR just allows type labels to do that (as is clarified above).

2023-03-27 14:33 UTC, jrgissing commented on doc/src/set.rst
> +Keywords *type/ratio* and *type/subset* also set the atom type or atom
See my earlier comment

2023-03-27 14:33 UTC, jrgissing commented on doc/src/set.rst
> +specified value from 1 to nbondtypes (nangletypes, etc). One can also use
this looks good

2023-03-27 14:38 UTC, jrgissing commented on doc/src/set.rst
> +Keyword *type* sets the atom type or atom type label for all selected atoms.
here is another occurrence

2023-03-27 15:31 UTC, yafshar commented on doc/src/set.rst
> +Keyword *type/fraction* sets the atom type or atom type label for a fraction
@jrgissing, thanks. I see your point, so do you suggest removing the "or atom type label" here?  So should it be as before "Keyword *type/fraction* sets the atom type for a fraction"

2023-03-27 16:14 UTC, jrgissing commented on doc/src/set.rst
> +Keyword *type/fraction* sets the atom type or atom type label for a fraction
yes, i think that is more correct

2023-03-27 16:15 UTC, jrgissing approved these changes

2023-03-27 22:44 UTC, sjplimp requested changes
Hi @yafshar - two things:

(a) I pushed a new set.rst file with suggested edits for the doc page to make things more clear.
(b) Several places in the new set.cpp and now once in atom.cpp, you are overwriting one of the vector values passed in by char **arg, with a new char * string created by utils::expand_type().  And then you are doing a delete [] of that char * string within set.cpp of atom.cpp.

This seems wrong to me, since input.cpp will later try to deallocate its own char **arg data ?
In a stylistic sense, I don't think set.cpp or atom.cpp methods should be changing the char **arg data passed to it from Input.

@akohlmey can comment on this better than me

2023-03-27 23:27 UTC, yafshar commented
> utils::expand_type(

@sjplimp, thanks for the edit. It makes this more clear. Regarding the `utils::expand_type`, I was thinking the same, but looking at the function it returns a new temporary array `new char` using 
https://github.com/lammps/lammps/blob/b8ff478d7874a2ae0ef9402fc4728a77e87214a4/src/utils.cpp#L862
https://github.com/lammps/lammps/blob/b8ff478d7874a2ae0ef9402fc4728a77e87214a4/src/utils.cpp#L999 and @akohlmey pointed out that if I do not delete these temporary arrays, I will introduce memory leaks.

2023-03-27 23:29 UTC, jrgissing commented
> In a stylistic sense, I don't think set.cpp or atom.cpp methods should be changing the char **arg data passed to it from Input.

I was originally okay with this idea (similar to an immediate variable evaluation using 'label2type') because all the internal lammps code assumes the argument is a numeric type

2023-03-27 23:43 UTC, yafshar commented
> > In a stylistic sense, I don't think set.cpp or atom.cpp methods should be changing the char **arg data passed to it from Input.

@sjplimp @akohlmey, if it is not OK to overwrite *arg, we can avoid that. It only duplicates the lines. For example,

```c++
char *typestr = utils::expand_type(FLERR,arg[iarg+1],Atom::ATOM,lmp);
if (typestr) ivalue = utils::inumeric(FLERR,typestr,false,lmp);
else ivalue = utils::inumeric(FLERR,arg[iarg+1],false,lmp);
delete[] typestr;
```

2023-03-28 00:07 UTC, sjplimp commented
@yafshar yes, the issue is not deleting the string which utils::expand_type() allocated - that is necessary

the issue is overwriting the pointer in args (allocated and managed by the input class)

2023-03-28 01:49 UTC, akohlmey commented
I agree that conceptually it is problematic to overwrite the pointers for the individual "words" in the `arg` list, because you don't know how they were allocated (e.g. there could be a mismatch between new/delete and malloc/free, newer code uses the former, older code the latter).

> the issue is overwriting the pointer in args (allocated and managed by the input class)

In this case, it works out by chance, because the "words" are not individually allocated, but they are pointers into a string buffer with the entire line of input after applying all substitutions. Thus the "words" are not individually deallocated, but just the entire buffer and *that* pointer cannot be modified by overwriting any of the "arg" list pointers.

2023-03-28 02:08 UTC, akohlmey commented
> It only duplicates the lines.

Not necessarily. In fact, you can get rid of the assignment and write this so only one line is added.
```
       char *typestr = utils::expand_type(FLERR, arg[iarg + 1], Atom::ATOM, lmp);
       ivalue = utils::inumeric(FLERR, typestr ? typestr : arg[iarg + 1], false, lmp);
```

2023-03-28 02:12 UTC, yafshar commented
> > It only duplicates the lines.
> 
> Not necessarily. In fact, you can get rid of the assignment and write this so only one line is added.
> 
> ```
>        char *typestr = utils::expand_type(FLERR, arg[iarg + 1], Atom::ATOM, lmp);
>        ivalue = utils::inumeric(FLERR, typestr ? typestr : arg[iarg + 1], false, lmp);
> ```

@akohlmey I fixed the copy to arg. If you rather have one line as you suggested, I can revert the change.

2023-03-28 02:14 UTC, akohlmey commented
> @akohlmey I fixed the copy to arg. If you rather have one line as you suggested, I can revert the change.

Yes, duplicating code should be avoided. Every line of code that does not need to be written is automatically bug free.

2023-03-28 02:33 UTC, akohlmey commented
@yafshar please run "make fix-whitespace" in the src folder and commit any changes.
The SetProperty unit test was failing on MacOS, so please keep an eye on that.

2023-03-28 19:41 UTC, sjplimp approved these changes
@yafshar Thanks for making these changes

2023-03-28 19:42 UTC, sjplimp commented
@akohlmey Ready to merge from my perspective

2023-03-28 20:07 UTC, merged