informational thermo column titles
lammps/lammps pull request #3764
Opened 2023-05-02 05:58 UTC by jrgissing

**Summary**

Replace indexed computes and fixes in thermo output column titles with descriptions of what is being outputted, for more self-descriptive logfiles. In most cases, it makes sense to do this by default instead of manually modifying the column name. Current draft PR is a specific demo for fix bond/react. Instead, of 'f_my_rxns[1]' as the thermo output column title, the column title is the name of the reaction, such as 'Diels-Alder'. 

TODO: make more general and expand to computes/fixes where it makes sense

**Related Issue(s)**

none

**Author(s)**

JG

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

only possible concern is hard-coded post-processing tools that assume previous non-descriptive titles

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2023-05-02 14:45 UTC, akohlmey commented
I see a few cases where this could be useful, e.g. for compute reduce where it could say "sum(xxx)" or "min(xxx)", but for the most part, the manual option with fix_modify is fully sufficient and preferable. It would be preferable, if you could just call thermo_modify from your fix, if needed, but that would probably need adding some functions there.

What bothers me a lot is that this change modifies long established default behavior and that there is no option to recover that old behavior. Some post-processing tools people have written depend on the default behavior and I suspect it may also break PyLammps.

2023-05-02 16:04 UTC, jrgissing commented
I see your points. Another specific example I had in mind was fix nvt/npt, where the output can change based on user settings and is somewhat indecipherable when the variable names are not included in the column title. In cases like these, it seems preferable to make the self-describing version the default. If we proceed in this way for certain fixes/computes, I can include an option to recover old behavior.

2023-05-05 15:13 UTC, jtclemm commented
There was a short discussion about a related idea on slack a year or so ago revolving around ambiguous dump column names in compute X/local and property/X commands. I don't think an ideal solution was found, but Axel added the option to manually rename individual columns in thermo/dump files in #3197.

If this PR identifies a good way to automatically generate descriptive thermo column names, a similar option might be helpful for dump files.

2024-05-13 19:59 UTC, stanmoore1 commented
@jrgissing do you have more changes for this PR, or is it ready for review?

2024-05-13 20:09 UTC, jrgissing commented
> @jrgissing do you have more changes for this PR, or is it ready for review?

This PR is still is progress, and will need significant additions based on requests from @sjplimp

2025-01-16 16:46 UTC, akohlmey commented
@jrgissing this is currently our oldest pending pull request. Do you have any comments on the status?
I am particularly concerned about these kinds of useful-but-potentially-disruptive changes and would like to have them merged early in the development cycle between stable releases.

2025-01-21 06:14 UTC, jrgissing commented
In my opinion, this PR could be merged as is (after I add docs and re-review it), with the idea that it establishes the framework for 'informational thermo column titles', and that support for specific fix/computes can be added as requested. Note that Steve requested a significant set of enhancements to this idea (I could clean up and post our offline discussion here, for reference), but those additional features will likely take me a while to get around to

2025-11-10 20:30 UTC, jtclemm commented on doc/src/compute_reduce.rst
> +   compute 3 all reduce max c_1[1] c_1[2] c_2 replace 1 3 replace 2 3 inputs local
Admittedly, I struggled parsing how this example led to 'c_3:c_1[1]<-max(c_2)'. Since this example is supposed to help users follow the syntax, could compute 1 & 2 be renamed something more distinct like myProp and myBond? Or even A and B?

Between compute names, indices, and replacement vecs, there are a lot of 1, 2, and 3 integers. The above example with myPress was much clearer.

2025-11-11 05:29 UTC, jrgissing commented on doc/src/compute_reduce.rst
> +   compute 3 all reduce max c_1[1] c_1[2] c_2 replace 1 3 replace 2 3 inputs local
nice idea! done.

2025-11-11 15:02 UTC, jtclemm approved these changes

2025-11-11 22:22 UTC, sjplimp commented
I'll take a look at this to refresh myself on the current status

2025-12-04 17:44 UTC, sjplimp commented on doc/src/thermo_modify.rst
> +computes.  The setting for *ID string* replaces the default text with the
make "The setting for ID ..." be a new paragraph

2025-12-04 17:45 UTC, sjplimp commented on doc/src/thermo_modify.rst
> +thermo keyword.  With a setting of *auto*, certain fixes or computes will
New paragraph for auto

2025-12-04 17:46 UTC, sjplimp commented on doc/src/thermo_modify.rst
New paragraph to describe what "default setting" does

2025-12-04 17:48 UTC, sjplimp commented on doc/src/thermo_modify.rst
> +nvt', 'fix npt', 'fix nph', 'compute reduce', and 'fix bond/react'.
Add a new paragraph to explain what "default" setting does

2025-12-04 17:50 UTC, sjplimp commented on doc/src/thermo_modify.rst
> +nvt', 'fix npt', 'fix nph', 'compute reduce', and 'fix bond/react'.
It is also not clear to me how the 3 options (ID, auto, default) interact with each other.  Does auto or default override all previous column-specific settings for ID ?  If so, that should be emphasized.  If not, then the details should be explained. Possibly auto/default only override column settings for fixes or computes ?

2025-12-04 17:55 UTC, sjplimp requested changes
Made a few suggestions for the thermo_modify.rst file.

I'm willing to approve this for merging if this is a stepping-stone to some of the further enhancements we talked about earlier?  If these changes will be discarded (or completely refactored) for the bigger picture, then I'm not sure it makes sense to merge this now?

2025-12-07 19:14 UTC, jrgissing commented
Yes, I believe this PR is a stepping stone that will not need to be refactored. For reference, the further enhancements you requested include adding similar support to dump_modify, and to other fixes (e.g., ave/atom), computes, or variables that could benefit from this feature.

2025-12-08 21:30 UTC, sjplimp approved these changes

2025-12-09 21:31 UTC, merged