Collected small changes and fixes
lammps/lammps pull request #3781
Opened 2023-05-17 14:32 UTC by akohlmey

**Summary**

This pull request combines multiple small changes and bugfixes.

**Related Issue(s)**

Addresses the issue reported here: https://matsci.org/t/python-gather-bonds-error/48618/
Fixes #3799
Addresses performance regression reported here: https://matsci.org/t/performance-degradation-in-neighbor-list-construction-in-openmp-package/48973

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- make sure the buffer for gathering bond/angle/dihedral/improper information is non-null and thus avoid a segfault
- correct minor inconsistencies in water model howto examples
- improve some error messages
- swap order of creating thermo and dump file output in order for dump styles that include thermo data to be in sync
- refactor how dump styles can access thermo data by creating an explicit cache of computed values
- add library interface API to access the cached thermo data
- fix bug when Kokkos border comm is on host
- fix performance regression when using multi-threaded neighbor list build in OPENMP package
- add support for atom type wildcards to fix reaxff/species
- use advanced fmtlib formatting to create column aligned output for fix reaxff/species instead of depending on tabs

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

2023-05-31 19:22 UTC, akohlmey commented
Note: the changes to the Output class may need extra testing. It has passed all tests I can trigger from GitHub.

2023-05-31 19:28 UTC, athomps approved these changes
I approve.

2023-05-31 19:31 UTC, stanmoore1 approved these changes

2023-06-07 17:01 UTC, rbberger requested changes
Nice addition, just avoid the copies.

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf_mpiio.cpp
> +    auto fields = output->thermo->get_fields();
These should both be `const auto &` to avoid copies.

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf_mpiio.cpp
> +      auto keywords = output->thermo->get_keywords();
Same here.

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf_mpiio.cpp
> +      auto keywords = output->thermo->get_keywords();
and here

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf.cpp
> +    auto fields = output->thermo->get_fields();
here

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf.cpp
> +        auto keywords = output->thermo->get_keywords();
here

2023-06-07 17:01 UTC, rbberger commented on src/NETCDF/dump_netcdf.cpp
> +        auto keywords = output->thermo->get_keywords();
here

2023-06-07 17:01 UTC, rbberger commented on src/EXTRA-DUMP/dump_yaml.cpp
> +      for (auto val : th->get_fields()) {
```suggestion
      for (const auto & val : th->get_fields()) {
```

2023-06-07 17:01 UTC, rbberger commented on src/EXTRA-DUMP/dump_yaml.cpp
> +      for (auto key : th->get_keywords()) thermo_data += fmt::format("{}, ", key);
```suggestion
      for (const auto & key : th->get_keywords()) thermo_data += fmt::format("{}, ", key);
```

2023-06-07 18:04 UTC, akohlmey commented on src/NETCDF/dump_netcdf_mpiio.cpp
> +    auto fields = output->thermo->get_fields();
Shouldn't this be automatic when Thermo::get_keywords() returns a const &?

2023-06-07 19:59 UTC, sjplimp approved these changes

2023-06-07 20:00 UTC, sjplimp commented
@akohlmey New thermo field access logic looks good - thanks for iterating with me on this change

2023-06-07 20:24 UTC, rbberger commented on src/NETCDF/dump_netcdf_mpiio.cpp
> +    auto fields = output->thermo->get_fields();
No. That's not how `auto` works. https://godbolt.org/z/e5zPYjbdT

2023-06-07 20:29 UTC, akohlmey commented
> New thermo field access logic looks good

Not quite done with that. Needed to make some tweaks so I can expose it to the library interface.
This is mostly done, but now the challenge it to get it into Python (and the other languages). To make it work with PyLammps instead of capturing and parsing the screen output, I may have to add an option to run a callback function whenever thermo output is created. But one step at a time...

2023-06-07 20:36 UTC, rbberger approved these changes

2023-06-07 20:36 UTC, rbberger commented
@akohlmey let me know if you want me to update the Python parts.

2023-06-07 20:41 UTC, akohlmey commented
> @akohlmey let me know if you want me to update the Python parts.

Let me see how far I get tomorrow. Next step is writing tests (and sorting out the failing ones).
Will have to think about what a good interface for python is. Perhaps returning a dict?
Then I need to propagate the function through the other language interfaces (fortran, swig, dlopen). They are all "complete" at the moment and I would like to keep it that way, especially since we are close to a stable release.

Writing tests is a good way to check whether the added interface is usable or needs more tweaks (or adding a companion function).

2023-06-08 14:31 UTC, jtclemm approved these changes
Looks good.

2023-06-08 19:19 UTC, akohlmey commented
@rbberger test and lammps module wrapper are added. PyLammps is going to be more work, especially if you want to use this internally, so I didn't touch that. Had to make a few small tweaks to make the interface work well enough with just one function call added.

Now looking into swig, fortran, and dlopen versions...

2023-06-08 19:40 UTC, rbberger commented
@akohlmey looks ok. Although I would have stuck with the void* cast and not use the static to keep the interface "thread-safe". but I'm not even sure that's something we're striving for anyway. `typ = cast(ptr, c_int).value` should have been enough instead of resetting the return type.

2023-06-08 19:48 UTC, akohlmey commented
> Although I personally would have stuck with the void* cast and not use the static to keep the interface "thread-safe".

I have tried hard and it works with ctypes, but GCC was throwing a fit when I tried to cast the void* back to an int when I was writing the unit test. The alternative would have been to use another union similar to ubuf and that would have failed on big endian machines (which are almost extinct, though) or required a maze of ifdefs to detect those. I decided that having to use a static variable in the library interface is the - by far - lesser evil.

2023-06-08 19:51 UTC, rbberger commented
@akohlmey Probably it's just telling us that the cleaner way would be to add a second function.

2023-06-09 02:03 UTC, merged