Standardize how computes and fixes can produce multiple kinds of output
lammps/lammps pull request #3896
Opened 2023-08-21 17:09 UTC by sjplimp

**Summary**

Allow computes and fixes to produce mutliple styles (global, peratom, local, pergrid) and kinds (scalar, vector, array) of output data.  A few computes already did this, but the general rule was a single style or output per compute or fix.  This PR changes the documentation to say there are no restrictions.  A few changes to existing commands and the syntax for referencing compute/fix data from variables was needed to standardize the new data production and data access rules.

Specifically this PR does the following:

* updates doc pages for the new generality
*  compute voronoi/atom can now produce both peratom and local data
* compute reduce can now process either peratom or local data, but not both (in one command instance), an "inputs" keyword was added to disambiguate
* equal-style variables can access any scalar from global or peratom computes/fixes, using c_ID versus C_ID to disambiguate
* vector-style variables can only access global vectors from computes/fixes (or use an equal-style variable for any scalar data from a compute/fix)
* atom-style variables can only access peratom data from computes/fixes (or use an equal-style variable for any other scalar data from a compute/fix)

**Related Issue(s)**

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2023-08-21 17:10 UTC, sjplimp commented
@akohlmey @stanmoore1 Full regression testing (unit, example scripts) should be done on this PR, before merging

2023-08-21 17:13 UTC, sjplimp commented
@akohlmey I still need to check the Programmer Guide for doc updates on compute/fix outputs

2023-08-22 16:34 UTC, akohlmey commented
@sjplimp found and fixed one bug. Running full test suite now.
Please remember to run "make fix-whitespace" in `src` before committing.

2023-08-22 16:50 UTC, sjplimp commented
@akohlmey Do not see any PG changes that are needed

2023-08-22 17:58 UTC, akohlmey commented
@sjplimp tests derived from the following example inputs are failing:
- snap/in.snap.compute
```
ERROR: Variable db_2_25: Mismatched compute in variable formula (src/variable.cpp:1550)
```
- in.snap.compute.quadratic
```
ERROR: Variable db_2_100: Mismatched compute in variable formula (src/variable.cpp:1550)
```
- voronoi/in.voronoi
```
ERROR: Variable d5a: Mismatched compute in variable formula (src/variable.cpp:1550)
```
- voronoi/in.voronoi.data
```
ERROR: Illegal compute voronoi/atom command (src/VORONOI/compute_voronoi_atom.cpp:114)
Last command: compute 	v2 all voronoi/atom neighbors yes edge_histo 6 peratom no
```
```

2023-08-22 21:57 UTC, sjplimp commented
@akohlmey Fixed 3 of the 4 with new syntax in the input scripts.  However for voronoi/in.voronoi.data there seems to be a code issue in compute_voronoi_atom.cpp which I don't understand.  If I put this printf() as the first line of the constructor:
printf("CR CONSTRUCTOR: UNDECIDED PERATOM LOCAL %d %d %d\n",UNDECIDED,PERATOM,LOCAL);
I get this result:
CR CONSTRUCTOR: UNDECIDED PERATOM LOCAL 0 0 1
which is messing up the logic for peratom vs local below and throwing an error.
How is the enum{} giving those 3 values?
Maybe some collision with PERATOM defined elsewhere?

2023-08-22 21:58 UTC, sjplimp commented
ah, now I see that enum is redefined (differently) in the compute_reduce.h file.  Is that the preferred place for it now?

2023-08-22 22:02 UTC, sjplimp commented
ok - fixed the 4th input script now

2023-08-22 22:05 UTC, akohlmey commented
> ah, now I see that enum is redefined (differently) in the compute_reduce.h file. Is that the preferred place for it now?

If you need constants that are defined consistently across multiple computes, they should be defined in compute.h and the equivalent instances in individual .h or .cpp files should be eliminated. If non-computes need to access them, they can use `Compute::<NAME>`.

2023-08-22 22:13 UTC, akohlmey requested changes
There seems to be some upper/lower case mixup in the variable docs.

2023-08-22 22:13 UTC, akohlmey commented on doc/src/variable.rst
> +| equal  | F_ID{i}[J] | element of per-atom array (I = atom ID)  |
```suggestion
| equal  | F_ID[I][J] | element of per-atom array (I = atom ID)  |
```

2023-08-22 22:13 UTC, akohlmey commented on doc/src/variable.rst
> +| equal  | C_ID{i}[J] | element of per-atom array (I = atom ID)  |
```suggestion
| equal  | C_ID[I][J] | element of per-atom array (I = atom ID)  |
```

2023-08-22 22:23 UTC, sjplimp commented on doc/src/variable.rst
> +| equal  | C_ID{i}[J] | element of per-atom array (I = atom ID)  |
good catch - done

2023-08-22 22:33 UTC, akohlmey commented
@sjplimp Can you please increment the version in src/version.h from "2 Aug 2023" to "3 Aug 2023".
This is hopefully small enough and only in the develop tree (which has the Development flag set as well) so that it won't make people think there was a new release. I need the difference for the automated testing, so can change the inputs in the regression test tree from, e.g.:
```
variable d5a equal c_v1[${i1}][1]
variable d5b equal c_v1[${i2}][1]
variable d5c equal c_v1[${i1}][2]
variable d5d equal c_v1[${i2}][2]
```
to 
```
if $(version<=20230802) then &
  "variable d5a equal c_v1[${i1}][1]" &
  "variable d5b equal c_v1[${i2}][1]" &
  "variable d5c equal c_v1[${i1}][2]" &
  "variable d5d equal c_v1[${i2}][2]" &
else &
  "variable d5a equal C_v1[${i1}][1]" &
  "variable d5b equal C_v1[${i2}][1]" &
  "variable d5c equal C_v1[${i1}][2]" &
  "variable d5d equal C_v1[${i2}][2]"
```
and thus have the tests working for both, the stable version *and* the development branch.

2023-08-22 22:57 UTC, akohlmey commented
@sjplimp voronoi tests still have problems. Please see attached comparing outputs for the "fixed" regression test inputs for the stable version and your pull request.
[log.voronoi.data.new.txt](https://github.com/lammps/lammps/files/12413530/log.voronoi.data.new.txt)
[log.voronoi.data.old.txt](https://github.com/lammps/lammps/files/12413531/log.voronoi.data.old.txt)
[log.voronoi.new.txt](https://github.com/lammps/lammps/files/12413534/log.voronoi.new.txt)
[log.voronoi.old.txt](https://github.com/lammps/lammps/files/12413535/log.voronoi.old.txt)

2023-08-23 17:53 UTC, akohlmey approved these changes

2023-08-23 17:54 UTC, akohlmey commented
@sjplimp all checks pass now on the CI test servers and GitHub. @stanmoore1 this is in your hands now.

2023-08-23 21:03 UTC, akohlmey commented
@sjplimp can you please draft a little text for the "Backward Compatibility" section of the release notes that summarizes the result of this PR?

2023-08-24 13:06 UTC, sjplimp commented
@akohlmey I added the info at the top of this page - can't find the future Release notes page

2023-10-16 17:57 UTC, stanmoore1 commented
Looking at the code, I don't see anything that needs to be ported Kokkos. I will run this through full Kokkos regression testing though just to be safe.

2023-10-16 18:16 UTC, stanmoore1 approved these changes
Code looks OK to me

2023-10-16 22:09 UTC, stanmoore1 commented
Regression tests passed, this is ready to merge from my POV.

2023-10-16 22:12 UTC, merged