GPU package updates Dec 2023
lammps/lammps pull request #4009
Opened 2023-12-11 15:50 UTC by ndtrung81

**Summary**

This PR contains updates and maintenance to the GPU package: adding the GPU version of several pair styles: lj/cut/coul/long/soft,  lj/cut/coulcut/soft, coul/long/slater, edpd, mdpd, sph/lj, sph/taitwater, sph/heatconduction; updating the corresponding doc pages, and cleaning up unused variables.

**Related Issue(s)**

coul/long/slater is added per Feature Request issue #3918 

**Author(s)**

Trung Nguyen (U Chicago)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should maintain backward compatibility

**Implementation Notes**

1. The pair styles from DPD-MESO and SPH packages demonstrate how to use the extra arrays to store extra_field per-atom data in the GPU package, and how to accumulate/tally per-atom values within the kernels. This is an option to refactor existing Base* classes and to support other AtomVec* classes with extra per-atom data.

2. The pair styles mdpd_rhosum and sph_heatconduction do not calculate atom forces, energy and virial, but rather tallying per-atom values, which are reminiscent of computing density rho in pair eam, and so can be lumped into the actual pair styles.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2023-12-12 18:01 UTC, stanmoore1 requested changes
Need to update Commands list, https://github.com/lammps/lammps/blob/develop/doc/src/Commands_pair.rst. Otherwise looks fine to me.

2023-12-13 05:13 UTC, ndtrung81 commented
@stanmoore1 thanks, I updated `Command_pair.rst` and fixed some last-minute issues.

2023-12-13 08:55 UTC, akohlmey approved these changes

2023-12-13 16:27 UTC, stanmoore1 approved these changes

2023-12-13 16:59 UTC, merged