Update ML-IAP for ACE support
lammps/lammps pull request #4078
Opened 2024-02-14 23:23 UTC by jmgoff

**Summary**

The ML-IAP package is updated to support ACE descriptors and models. Previously ML-IAP could not support ACE descriptor computes or ACE models (including linear, neural network, and more general non-linear models).  

Key enhancements and features are:

- LAMMPS-native support for arbitrary ACE pytorch models (including neural networks)
-- Users can run arbitrary ACE neural network poentials in LAMMPS, calculate energies, forces, and stresses
- Ability for users to separate linear model coefficients and clebsch-gordan coefficients (offers a more general format for ACE models developed from different software)
-- This may help serve as a template to simplify ACE inputto a single list of coefficients in the future
- Ability to use ACE descriptors in general mliappy/python routines (e.g. in structure generation algorithms, model training, and on-the-fly analysis)
- Various examples for ML-IAP + ACE are provided

**Related Issue(s)**

N/A

**Author(s)**

James Goff (Sandia National Laboratories) ( [goffjimmy1@gmail.com](mailto:goffjimmy1@gmail.com) )

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Will not break backward compatibility 

**Implementation Notes**

ACE support in mliap uses functions from the ML-PACE package, and updates were made to import new ACE descriptor evaluators implemented by the owners of the ML-PACE package. This largely required the development of a new mliap descriptor class in`src/ML-IAP/mliap_descriptor_ace.*` - and minor adjustments throughout the mliap package to accommodate the new class.

To validate the results for the mliap implementation of ACE descriptors and models:
The mliap ace compute reproduces descriptor values, descriptor gradients, and virial terms from`compute pace`. 
The energies, forces, and stresses were validated for mliap ACE models (including pytorch neural networks)  the `numdiff` fix.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2024-02-15 00:35 UTC, jmgoff commented
Similar to the ML-IAP  python models requiring that PKG_PYTHON is installed, the ML-IAP ACE descriptors require that PKG_ML-PACE is also installed. This crashed some unit tests before because ML-PACE is not included by default.

Resolved by adding a new compilation flag: `-DMLIAP_ENABLE_ACE` that can only be turned on if `-DPKG_ML-PACE` is on.

To use ML-IAP & ACE functionality, compile lammps with the following dflags (in addition to the dflags required for Python and ML-IAP:
`-DPKG_ML-PACE=yes`
`-DMLIAP_ENABLE_ACE=yes`

2024-02-15 01:04 UTC, akohlmey requested changes
This will need updates to the documentation.
Also, I only see support for the CMake build system. What about the traditional build with GNU make?

2024-02-15 01:08 UTC, akohlmey commented
Since both ML-IAP and ML-PACE have KOKKOS versions, does this PR need some KOKKOS updates?

2024-02-20 23:23 UTC, athomps commented
> Since both ML-IAP and ML-PACE have KOKKOS versions and also mliappy has KOKKOS support, does this PR need some KOKKOS updates?

The same functionality already exists for SNAP descriptors, but these have not yet been Kokkosized in MLIAP.  I think this will happen soon, but until then, it is better not to attempt it for ACE descriptors, which are quite a bit more complicated than the SNAP descriptors

2024-02-21 01:16 UTC, akohlmey commented
> but until then, it is better not to attempt it for ACE descriptors

Then there should be some tests implemented that prevent using this with KOKKOS or someone needs to explain how this cannot produce problems with the current code if somebody tries this.

2024-02-21 01:17 UTC, akohlmey commented on cmake/Modules/Packages/ML-IAP.cmake
> +option(MLIAP_ENABLE_PYTHON "Build ML-IAP package with Python support" ${MLIAP_ENABLE_PYTHON_DEFAULT})
This is replicated from line 11

2024-02-21 01:17 UTC, akohlmey commented on src/ML-IAP/mliap_descriptor_ace.cpp
> +#define MAXLINE 1024
These two defines are not used anywhere.

2024-02-21 01:19 UTC, akohlmey commented on src/ML-IAP/mliap_descriptor_ace.cpp
> +//#include <map>
Please remove commented out code like this.

2024-02-21 01:19 UTC, akohlmey commented on src/ML-IAP/mliap_descriptor_ace.cpp
> +#include <typeinfo>
Is this include file needed?

2024-02-29 18:51 UTC, stanmoore1 commented
I am OK with Aidan's suggestion of waiting on adding Kokkos support for ACE/SNAP. So I think this PR can be merged after addressing Axel's feedback.

2024-03-12 16:24 UTC, akohlmey commented
@jmgoff FYI, I've merged this branch with upstream and resolved a merge conflict due to recently added functionality.

2024-03-22 15:44 UTC, athomps approved these changes
I approve

2024-03-22 15:48 UTC, stanmoore1 requested changes
Need to error out if a user tries to use the Kokkos version of ML-IAP with ACE or SNAP descriptors, something like this:

```
if (lmp->kokkos) error->all(FLERR,"Cannot (yet) use KOKKOS package with SNAP descriptors");
```

2024-03-22 23:22 UTC, jmgoff commented
Thank you all for the comments and reviews. The most recent pushes should address the remaining comments and issues. To summarize:
For Axel's previous comments:
-Documentation has been updated and added for ace in MLIAP
-Cleaned up leftover comments, defines, and whitespace in docs
-Support for make added. Updated ML-IAP make file setup from `ML-IAP` to allow for optional ace descriptor use (requiring that ML-PACE is also built) 
For Aidan's comments:
-Standard g++ (1 core) and (4 core) outputs have been added for the new MLIAP/ace examples
To address comments from Axel, Stan, and Aidan on the use of kokkos:
-Following Stan's comment this morning and previous discussion, checks have been added to `pair_mliap.cpp` and `compute_mliap.cpp` to throw runtime errors when users attempt to use `mliap/kk` with SNAP or ACE in mliap computes or pair styles.

2024-03-23 03:41 UTC, akohlmey commented
@jmgoff both CMake and GNU make support were incorrect or incomplete. I have tried to fix it.

There were still some style issues that I resolved and I also applied clang-format to make the programming style consisten. I also reordered the initializer list of the MLIAPData class to avoid compiler warnings.

2024-03-23 03:57 UTC, akohlmey approved these changes

2024-03-25 18:05 UTC, jmgoff commented
> @jmgoff both CMake and GNU make support were incorrect or incomplete. I have tried to fix it.
> 
> There were still some style issues that I resolved and I also applied clang-format to make the programming style consistent. I also reordered the initializer list of the MLIAPData class to avoid compiler warnings.
> 
> Since CPU snap descriptors are no longer allowed for KOKKOS, they corresponding unit tests need to be skipped.

Hi Axel, thanks for applying the extra corrections for the CMake and gmake scripts along with the styling issues. I'll keep an eye out for similar things in the future.

As long as you and @stanmoore1 are okay with disabling mliap/kk + CPU snap for now, this sounds good to me.

2024-03-25 18:14 UTC, stanmoore1 commented
Does it need to be disabled for Kokkos? i.e. does it give the wrong answer, or is it just slow but still works correctly?

2024-03-27 00:05 UTC, jmgoff commented
That is a good point. SNAP is only crashes for the mliappy model, not for the linear, quadratic, or NN models. I'll add in errors for the mliappy model specifically to make sure that we don't have to turn off unit tests that work.

2024-04-03 23:02 UTC, jmgoff commented
Adjusted it to only have ACE + mliap kokkos disabled and turned unit tests back on for SNAP + mliap kokkos. The SNAP mliappy model example works as well with the SNAP CPU descriptors.

2024-04-04 00:56 UTC, akohlmey commented
@stanmoore1 this is now waiting on you

2024-04-16 21:33 UTC, stanmoore1 approved these changes
A few minor doc issues, otherwise looks good.

2024-04-16 21:33 UTC, stanmoore1 commented on doc/src/pair_mliap.rst
> +multiplied by linear or square root embedding terms. In other words,
Typo: "multiplied multiplied" (occurs twice)

2024-04-16 21:33 UTC, stanmoore1 commented on doc/src/pair_mliap.rst
> +also built with the PYTHON package. As with other, the *mliappy* model style
"As with other," ... not sure what this means or what "other" refers to?

2024-04-17 02:42 UTC, merged