new added pairstyle and their kokkos version for bond valence and bon…
lammps/lammps pull request #4225
Opened 2024-07-05 15:04 UTC by pcplak

…d valence vector

**This added two new pair styles: bond valence, bond valence vectors. Bond valence and bond valence vectors are calculated for each atom in the pairstyle, and they are used to determine forces, energy, and virials. **

**The issue with this is that, the kokkos version running on GPU gives out different forces on each atom then kokkos version running on CPU or no kokkos running on cpu, which leads to inconsistency in the minimization step before molecular dynamics.**

**Peter Chun Pang Li(peterchunpang@gmail.com), Chuanfu Luo (luochuanfu@gmail.com), Shi Liu (liushi@sas.upenn.edu)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2024-07-05 20:08 UTC, stanmoore1 commented
@pcplak could you add an example that exercises the code and shows the differences in forces?

2024-07-05 21:54 UTC, pcplak commented
Yes of course. "inputdebug.lammps" is the input script that I use to run simulation for only 1 timestep and shows the difference in forces. There is no difference in 40 atoms, there are differences with 5000 atoms as shown in the result files. I have also attached my sbatch script if needed. In these simulations,  I compiled lammps including only the kokkos version for pair_bvv pairstyle,so the other two potentials defaulted to regular cpu potential files while running. The forces and other things from the results are computed for pair_bvv pairstyle specifically. This is done by adding "fprint" statements in pair_bvv.cpp and pair_bvv_kokkos.cpp files. Let me know if you need other things. Thanks!

[cpu 40 atoms result.txt](https://github.com/user-attachments/files/16113872/cpu.40.atoms.result.txt)
[cpu 5000 atoms result.txt](https://github.com/user-attachments/files/16113873/cpu.5000.atoms.result.txt)
[gpu 40 atoms result.txt](https://github.com/user-attachments/files/16113874/gpu.40.atoms.result.txt)
[gpu 5000 atoms result.txt](https://github.com/user-attachments/files/16113875/gpu.5000.atoms.result.txt)
[inputdebug.lammps.txt](https://github.com/user-attachments/files/16113876/inputdeb
[run.sh.txt](https://github.com/user-attachments/files/16113877/run.sh.txt)
ug.lammps.txt)

2024-07-05 21:55 UTC, pcplak commented
[inputdebug.lammps.txt](https://github.com/user-attachments/files/16113950/inputdebug.lammps.txt)
[run.sh.txt](https://github.com/user-attachments/files/16113951/run.sh.txt)

2024-07-12 21:00 UTC, stanmoore1 commented
Need `pmwlammps.data` to run the example.

2024-07-12 22:38 UTC, pcplak commented
[pmwlammps.data.txt](https://github.com/user-attachments/files/16199769/pmwlammps.data.txt)
[pmwlammps120.data.txt](https://github.com/user-attachments/files/16199770/pmwlammps120.data.txt)
[pmwlammps200.data.txt](https://github.com/user-attachments/files/16199773/pmwlammps200.data.txt)
[pmwlammps280.data.txt](https://github.com/user-attachments/files/16199774/pmwlammps280.data.txt)
[pmwlammps360.data.txt](https://github.com/user-attachments/files/16199775/pmwlammps360.data.txt)

2024-07-15 20:03 UTC, pcplak commented
Hi Stan, following up on our discussion in the lammps forum here, with regard to pack_forward_comm_kokkos and pack_forward_comm_kokkos functions in pair_bvv_kokkos, since their args are different from the functions in KokkosBase.h , couldn’t I just use function overloading? Or do I need to add another function with the same arguments as the function in pair_bvv_kokkos in the KokkosBase.h and then override that? Thanks!

2024-07-16 19:51 UTC, stanmoore1 commented
In order to override, you have to have the same function arguments that match `KokkosBase.h`.

2024-07-22 15:47 UTC, stanmoore1 commented
@pcplak in other words, the buffer is always a 1D array, and you need to pack/unpack multiple values for positions (`x[0]`, `x[1]`, `x[2]`) sequentially into the 1D buffer. You also need to set the number of datums = 3 in the constructor so the buffer doesn't run out of space. Let us know if you have questions on this.

2024-07-24 20:51 UTC, pcplak commented
I see! I will fix it in the way you suggested. Thank you!

2024-10-01 16:07 UTC, stanmoore1 commented
@pcplak any update on this pull request? Let me know if you need help with `pack_forward_comm_kokkos` and `unpack_forward_comm_kokkos` functions in `pair_bvv_kokkos`.

2024-10-01 16:56 UTC, pcplak commented
Thank you for checking in Stan. As I am in the middle of the school's semester as well as applying for grad school, I have not been making updates on this. I will update this in my winter break in December/January.

2025-01-16 16:16 UTC, akohlmey commented
@pcplak can you please give us another update on the status of this pull request?
If it won't be ready for a while, would you mind closing it (for now) and resubmitting when it is closer to completion?

2025-01-17 04:23 UTC, pcplak commented
Thanks for checking in. I have worked on the code, and once I have it tested on NERSC, I will provide more detailed update (as NERSC is doing their yearly node hours allocation currently, and our research group is requesting and reallocating hours to different account, which should be done soon.)

2025-01-23 01:08 UTC, pcplak commented
Thank you for your advice Stan! After I have made those changes and ran it on NERSC, the gpu result has identical energy with the cpu result; however, the initial pressure differs by a lot, any recommendation for debugging that?

2025-01-23 01:12 UTC, stanmoore1 commented
> Thank you for your advice Stan! After I have made those changes and ran it on NERSC, the gpu result has identical energy with the cpu result; however, the initial pressure differs by a lot, any recommendation for debugging that?

If the pressure on timestep 0 is wrong, likely the forces are likely wrong too, since those are related to the pressure.

Is the Kokkos Serial backend on CPU correct now, even with `-pk kokkos comm device`?

2025-01-27 00:21 UTC, pcplak commented
Yes the using KOKKOS on CPU backend gives me exact forces and pressure as the desired output.

2025-04-06 00:57 UTC, akohlmey commented
@pcplak Can you please give an update on the status of this pull request? It has been sitting idle since January. It probably needs to be updated with all the changes made to upstream and re-tested.
Please consider closing the pull request and re-submitting, if you are not planning to complete this soon.

2025-04-07 00:05 UTC, pcplak commented
> @pcplak Can you please give an update on the status of this pull request? It has been sitting idle since January. It probably needs to be updated with all the changes made to upstream and re-tested. Please consider closing the pull request and re-submitting, if you are not planning to complete this soon.

I will close it for now, and resubmit and work on this in May or June.

2025-06-20 22:45 UTC, pcplak commented
Hi @stanmoore1 , I come back to finalize this pull request. The original problem was that I got exact agreement between CPU and GPU if I use: -pk kokkos comm/pair/forward no. We realized the problem is due to forward comm in pair_bvv_kokkos. Then I have made changes to pack_forward_comm_kokkos and unpack_forward_comm_kokkos functions in pair_bvv_kokkos and uploaded them, now I have the energy match between the correct result and the result from using the forward comm kokkos function on gpu, but the pressure doesn't match. For debugging, I have run it on cpu with -pk kokkos comm/pair/forward device , and I obtain exact match in both energy and pressure with the correct result. I will attach the output files and my testing input script and data file below. Let me know how I should proceed.

2025-06-20 23:58 UTC, pcplak commented
correctoutput.txt is the benchmark output file that I used to compare the energy and pressure, cubic15final.txt is the data file, inputhexbto.txt is the lammps input file, cpukokkosresult.txt is the output file that I debugged on cpu, and it has correct energy and pressure; gpukokkosresult.txt is the output file that I ran on gpu and it has correct energy and wrong pressure.  
[correctoutput.txt](https://github.com/user-attachments/files/20844036/correctoutput.txt)
[cubic15final.txt](https://github.com/user-attachments/files/20844037/cubic15final.txt)
[inputhexbto.txt](https://github.com/user-attachments/files/20844038/inputhexbto.txt)
[cpukokkosresult.txt](https://github.com/user-attachments/files/20844053/cpukokkosresult.txt)
[gpukokkosresult.txt](https://github.com/user-attachments/files/20844068/gpukokkosresult.txt)

2025-07-10 19:31 UTC, stanmoore1 commented
@pcplak I'm looking at this now. Can you please add examples that exercise the new pair styles that we can use for testing? Also I think it would be best to put these pair styles into `/src/EXTRA-PAIR`.

2025-07-10 19:33 UTC, stanmoore1 commented
Also I think we need a more descriptive name than `pair bv` and `pair bvv`. Perhaps `pair bondval` and `pair bondvalvec`.

2025-07-10 19:49 UTC, pcplak commented
Of course, the LAMMPS input file, data files, and expected output files(with correct energy and pressure) are all in the attachment from my last comment. They are all in .txt format in order to upload them.

2025-07-10 19:51 UTC, stanmoore1 commented
>the LAMMPS input file, data files, and expected output files(with correct energy and pressure) are all in the attachment from my last comment

Ah missed that, thanks!

2025-07-10 19:51 UTC, pcplak commented
I agree, they would be in extra_pair category, and the naming you gave sounds great. I will work on the documentation for these two pair styles.

2025-07-11 15:28 UTC, stanmoore1 commented
@pcplak I'm seeing crashes on both CPU without Kokkos and GPUs. I made some minor tweaks to your example but I don't think that should affect the trajectories. Here is the output from CPU without Kokkos:

```
       470    8361.30704 -213622.17891  14180.26289   2191.92508      0.00000 -233664.42016 -303806.15037 221815.82216     60.53374     60.53374     60.53374
ERROR on proc 0: Out of range atoms - cannot compute PPPM
For more information see https://docs.lammps.org/err0004 (../pppm.cpp:1825)
```

2025-07-11 15:31 UTC, stanmoore1 commented
Also I don't see any numerical differences between GPU and CPU--they both crash at the same point. Can you take a look?

2025-07-11 18:05 UTC, pcplak commented
okay, what are the changes that you made, I can only see that you change the timestep for the first NVT run from 1000 to 500. From the result you have at time step 470, it seems like the temperature is 8361K, which is unphysical for this specific structure and that is why it runs into error. Does the pressure agree with the cpu and gpu(kokkos) from your run?

2025-07-11 18:11 UTC, stanmoore1 commented
You can see the input I'm running here: https://github.com/lammps/lammps/pull/4225/files#diff-e96e485e433a0f028fc5378b6c09727fb4f1c7199381c5e9f03bf18c8e70d976. Can you please run this on your CPU with the latest changes in this PR (without Kokkos is fine) and see if it crashes?

2025-07-11 18:26 UTC, pcplak commented
> You can see the input I'm running here: https://github.com/lammps/lammps/pull/4225/files#diff-e96e485e433a0f028fc5378b6c09727fb4f1c7199381c5e9f03bf18c8e70d976. Can you please run this on your CPU with the latest changes in this PR (without Kokkos is fine) and see if it crashes?
> 
> > Does the pressure agree with the cpu and gpu(kokkos) from your run?
> 
> Yes, but both crash after a little less than 500 timesteps.

Yep, I will do that.

2025-07-11 21:17 UTC, pcplak commented
Yes, mine also terminates at step 470 by running LAMMPS from this PR. This is weird. It should not be the case; I will check over this inconsistency and update you.

2025-07-11 22:52 UTC, stanmoore1 commented
I reverted back to b55f567 and it doesn't crash, so I must have messed something up.

2025-07-11 23:19 UTC, stanmoore1 commented
Actually 0350eac crashes, so I think it is some change from updating to latest develop.

2025-07-12 00:03 UTC, stanmoore1 commented
I was wrong--even your first commit 341aabb crashes on 24 MPI ranks on a CPU (no Kokkos):
```
       320    7694.84740 -208454.32928  13050.53562   2096.22881      0.00000 -231283.39488 -396377.67949 221815.82216     60.53374     60.53374     60.53374
ERROR on proc 11: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
Last command: run 500
ERROR on proc 19: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
Last command: run 500
```

The temperature seems to be blowing up. Not sure what is going on, but the pair style (or example) seems unstable. If you can fix this issue or get a different example that runs, I can take another look, otherwise I'm out of ideas.

2025-07-14 18:31 UTC, pcplak commented
> I was wrong--even your first commit [341aabb](https://github.com/lammps/lammps/commit/341aabb977852627762d7b3035d5cee0e1651c27) crashes on 24 MPI ranks on a CPU (no Kokkos):
> 
> ```
>        320    7694.84740 -208454.32928  13050.53562   2096.22881      0.00000 -231283.39488 -396377.67949 221815.82216     60.53374     60.53374     60.53374
> ERROR on proc 11: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
> Last command: run 500
> ERROR on proc 19: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
> Last command: run 500
> ```
> 
> The temperature seems to be blowing up. Not sure what is going on, but the pair style (or example) seems unstable. If you can fix this issue or get a different example that runs, I can take another look, otherwise I'm out of ideas.

I will attempt to fix this issue and update you. Thank you very much.

2025-07-23 14:20 UTC, akohlmey commented
@pcplak I made some formal updates to your pull request:
- addressed some programming style issues (e.g. use C++ versions of C-style headers, removed unused/unneeded includes and remove redundant virtual keywords)
- apply clang-format
- update to the latest development code

I also noticed that there is no documentation. That *must* be added. We have no undocumented features in LAMMPS.

2025-07-29 04:08 UTC, pcplak commented
> @pcplak I made some formal updates to your pull request:
> 
> * addressed some programming style issues (e.g. use C++ versions of C-style headers, removed unused/unneeded includes and remove redundant virtual keywords)
> * apply clang-format
> * update to the latest development code
> 
> I also noticed that there is no documentation. That _must_ be added. We have no undocumented features in LAMMPS.

Thank you very much! Our group is working on this documentation, and we will upload that soon.

2025-07-29 04:22 UTC, pcplak commented
> I was wrong--even your first commit [341aabb](https://github.com/lammps/lammps/commit/341aabb977852627762d7b3035d5cee0e1651c27) crashes on 24 MPI ranks on a CPU (no Kokkos):
> 
> ```
>        320    7694.84740 -208454.32928  13050.53562   2096.22881      0.00000 -231283.39488 -396377.67949 221815.82216     60.53374     60.53374     60.53374
> ERROR on proc 11: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
> Last command: run 500
> ERROR on proc 19: Out of range atoms - cannot compute PPPM (../pppm.cpp:1830)
> Last command: run 500
> ```
> 
> The temperature seems to be blowing up. Not sure what is going on, but the pair style (or example) seems unstable. If you can fix this issue or get a different example that runs, I can take another look, otherwise I'm out of ideas.

@stanmoore1 I have figured out the issue. The unphysical case comes from the modifed pair_lj_cut_coul_long potential from our group, which has some differences with the official pair_lj_cut_coul_long potential.  Bond_val and bond_val_vec pairstyles with their KOKKOS version has no issues, as I also verify it on my end that both the energy and pressure match running full kokkos with GPU. The initial problem of mismatch in pressure when running full kokkos comes from I probably made some mistake when adapting the pair_lj_cut_coul_long_kokkos to fit our modified pair_lj_cout_coul_long pairstyle.

2025-08-04 17:31 UTC, stanmoore1 commented
@pcplak great, can you post a working example for testing?

2025-08-07 00:59 UTC, pcplak commented
> @pcplak great, can you post a working example for testing?

Of course, the input file and the data file that I posted on Jun 20th would work, as long as you have replaced the pair_lj_cut_coul_long.cpp, pair_lj_cut_coul_long_kokkos.cpp, with the slight modified ones shown in the attachment. It works 100% correct when running with or without kokkos on cpu and running without (kokkos comm/pair/forward) on GPU. To run full kokkos on GPU, I am still looking at the problem in pair_lj_cut_coul_long_kokkos.cpp that gives the wrong pressure but correct energy. 
[pair_lj_cut_coul_long.txt](https://github.com/user-attachments/files/21645326/pair_lj_cut_coul_long.txt)
[pair_lj_cut_coul_long_kokkos.txt](https://github.com/user-attachments/files/21645328/pair_lj_cut_coul_long_kokkos.txt)

2025-09-09 18:40 UTC, stanmoore1 commented
@pcplak thanks I will take a look when I get a moment.

2025-09-10 01:33 UTC, pcplak commented
Thanks! @stanmoore1 This type of molecular dynamics is called Bond Valence MD, and for it to work it needs bond valence, bond valence vector, and the modified lj_cut_coul_long in the attachment from my last comment (we deleted the attraction part of the lj potential in lj_cut_coul_long). Bond valence and Bond valence vector are good already, can we add this modified lj_cut_coul_long (maybe give it a different name) to the LAMMPS repository once the KOKKOS version of it is fixed, so that people can directly run BVMD once downloaded and compiled newest version of LAMMPS.

2025-10-08 20:40 UTC, pcplak commented
@stanmoore1 I figured out the issue. Now everything works for the full KOKKOS. The only difference between these four files and what is already on lammps for pair_lj_cut_coul_long pairstyle is the the init_one function in the pair_lj_cut_coul_long.cpp file, I have initialized both lj2 and lj4 to be 0 shown in the screenshot below. That will adapt this pairstyle to run bond valence molecular dynamics correctly. I have fully tested it, and it worked well. 

<img width="1592" height="1087" alt="Screenshot 2025-10-08 162856" src="https://github.com/user-attachments/assets/6e6ec5e5-4f10-49a4-be0f-98e95a42dced" />

[pair_lj_cut_coul_long_cpp.txt](https://github.com/user-attachments/files/22785494/pair_lj_cut_coul_long_cpp.txt)
[pair_lj_cut_coul_long_h.txt](https://github.com/user-attachments/files/22785495/pair_lj_cut_coul_long_h.txt)
[pair_lj_cut_coul_long_kokkos_cpp.txt](https://github.com/user-attachments/files/22785496/pair_lj_cut_coul_long_kokkos_cpp.txt)
[pair_lj_cut_coul_long_kokkos_h.txt](https://github.com/user-attachments/files/22785497/pair_lj_cut_coul_long_kokkos_h.txt)

2025-10-08 20:41 UTC, pcplak commented
I will upload all the documentations in the next couple of weeks.

2025-10-24 00:35 UTC, pcplak commented
Here is the documentation. 
[BVMD_LAMMPS_Documentation_v2 (1).docx](https://github.com/user-attachments/files/23110444/BVMD_LAMMPS_Documentation_v2.1.docx)

2025-10-24 00:38 UTC, akohlmey commented
> Here is the documentation. [BVMD_LAMMPS_Documentation_v2 (1).docx](https://github.com/user-attachments/files/23110444/BVMD_LAMMPS_Documentation_v2.1.docx)

Please have a look at: https://docs.lammps.org/Modify_requirements.html#reqdocumentation

2025-11-15 16:13 UTC, akohlmey commented
@pcplak and @stanmoore1 this has been sitting idle for a while, can you provide some updates on what is still pending and who will work on what when?

2025-11-15 21:58 UTC, pcplak commented
> @pcplak and @stanmoore1 this has been sitting idle for a while, can you provide some updates on what is still pending and who will work on what when?

Thanks for checking on this Axel. 
Tasks remaining:
-  Addressing any other code issues (waiting to hear back from Stan on my previous updates)
-  Fixing the documentation to adapt the correct format
I will work on fixing the documentation and give an update by the end of next week.

2025-11-24 05:30 UTC, pcplak commented
This is the updated documentation in the correct format. It is in txt format for upload reason, but it is written following rst. 
[pair_bvmd_plaintxt.txt](https://github.com/user-attachments/files/23702270/pair_bvmd_plaintxt.txt)

2025-12-10 17:12 UTC, stanmoore1 commented
@pcplak can you please address the suggested changes from copilot?

2025-12-17 17:45 UTC, pcplak commented
> @pcplak can you please address the suggested changes from copilot?

I have addressed all of them besides the documentation. The documentation I wrote account for both bondval and bondval_vec given the physics behind them only make sense together. I probably should run a few tests with these committed changes to double check they are all working correctly.

2026-04-28 17:55 UTC, pcplak commented
Hey, just following up on this pull request, would this be merged soon? Please let me know if there is anything I could do on my end. Thanks!

2026-04-28 17:57 UTC, stanmoore1 commented
@pcplak sorry for the delay! Yes this should be in the next patch release, just need to do some checks and a final review.

2026-04-28 17:59 UTC, pcplak commented
> @pcplak sorry for the delay! Yes this should be in the next patch release, just need to do some checks and a final review.

Got it. Thanks!

2026-05-22 16:08 UTC, stanmoore1 commented
I tested this on an H100, everything seems to be working. Ready to merge from my POV.

2026-05-22 17:06 UTC, stanmoore1 commented on doc/src/pair_bondval.rst
> +.. FIXME
FIXME needs to be resolved.

2026-05-22 17:15 UTC, akohlmey requested changes
@pcplak The documentation does not match the style that is used throughout LAMMPS. Please update accordingly. I've added the minimal formal requirements, but more is needed. See my FIXME comment which also points to a couple reference examples to compare to.

2026-05-22 18:30 UTC, stanmoore1 approved these changes
The PR looks good to me. However, @pcplak should carefully review the changes to the documentation done by copilot before merging.

2026-06-02 16:45 UTC, stanmoore1 commented
@pcplak friendly reminder to please review the AI-generated documentation for this pull request so we can get this merged.

2026-06-02 17:02 UTC, pcplak commented
> @pcplak friendly reminder to please review the AI-generated documentation for this pull request so we can get this merged.

Thanks for remainder. Will do.

2026-06-10 14:49 UTC, stanmoore1 approved these changes

2026-06-10 14:50 UTC, stanmoore1 commented
@akohlmey this is ready for merge from my POV.

2026-06-10 19:03 UTC, akohlmey approved these changes

2026-06-10 19:30 UTC, merged