docs: expand author list
lammps/lammps pull request #4256
Opened 2024-08-02 18:55 UTC by rbberger

**Summary**

Updates the documentation to expand the LAMMPS author list, similar to what already happened at https://lammps.org/authors.html

@lammps/core Let me know if you also want the pictures here. Also, we can still change the sorting as mentioned.

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2024-08-05 17:40 UTC, sjplimp approved these changes

2024-08-05 17:41 UTC, sjplimp commented
@rbberger We will likely talk about the ordering at the conf call next week.  So hopefully that will be resolved before the stable release, if you want to wait to merge this

2024-08-05 23:24 UTC, akohlmey requested changes
Yeah, I also think it is best to wait until after the meeting next week and use whatever is decided then.

2024-08-21 01:15 UTC, akohlmey approved these changes

2024-08-21 02:37 UTC, merged