Python and library API changes for computes
lammps/lammps pull request #4380
Opened 2024-11-12 20:49 UTC by rbberger

**Summary**

- ensures that fix python/invoke registers computes' next timestep
- add library API for clearing and adding new time steps

**Related Issue(s)**

#4360 

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

2025-01-14 13:01 UTC, akohlmey requested changes
@rbberger I tried to resolve the merge conflict and looked into propagating the library interface extension to all the other related interfaces (Fortran, plugin, SWIG), but ran into some issues due to the use of the "bigint" versus "int" type.

Even though it is counter-intuitive, it would be easier to make this portable by making the nextstep argument of the compute_addstep variants a (void?) pointer. The correct size could easily be recovered *inside* the function from the size defines and we can extract the size of an bigint though the interface for the calling code and thus call the function with the correct argument (or just exit with a runtime error, if there is a mismatch). That would also allow to get rid of the ifdef in the function prototype in library.h and simplify extracting the documentation.

Also, for a person that occasionally programs LAMMPS itself, the names of the library functions are a bit unexpected. I would have expected those to be called `lammps_clearstep_compute()` and `lammps_addstep_compute()` and `lammps_addstep_compute_all()` to align better with the corresponding methods in the Modify class.

2025-01-19 23:07 UTC, rbberger commented
@akohlmey did the changes you mentioned. don't have anything against them.

2025-01-20 03:02 UTC, akohlmey commented
> @akohlmey did the changes you mentioned. don't have anything against them.

@rbberger Thanks a lot. I appreciate it. I will look into it when I have a bit more time. Currently wrestling with GPFS troubles when updating from CentOS 7 to MultiLinux (aka Liberty Linux) 7.

2025-01-27 19:35 UTC, akohlmey approved these changes

2025-01-27 19:40 UTC, akohlmey commented
@rbberger have 90% of the missing changes done. Am lacking a good idea for how to test python and fortran. Do you have something, so you can check that I didn't mess up something that you need?

If you want, we can merge "as is". I will need to do a general "sync" of the various types of interfaces build on top of the LAMMPS C-style library interface at some time in the future.

2025-01-28 02:03 UTC, akohlmey commented
The two missing Fortran interface functions are added.

2025-01-28 03:42 UTC, sjplimp commented on src/PYTHON/fix_python_invoke.cpp
> +  modify->clearstep_compute();
Can you add a comment line or two to explain why you are wrapping the callback with clearstep/addstep?
I.e. in case the Python method accesses compute info that depends on pair energy/virial data being calculated on specific timesteps.   Ditto at the end of the constructor.

2025-01-28 03:49 UTC, sjplimp commented on src/PYTHON/fix_python_invoke.cpp
> +  modify->clearstep_compute();
And ditto in post_force().

2025-01-28 15:04 UTC, sjplimp commented
@rbberger I believe there is a subtle issue with the use of addstep_compute_all() in fix python/invoke being only in the constructor.

If the input script logic is this:

fix ... python/invoke 100 post_force ,,,     # called every 100 steps
minimize ...   # runs for 125 steps
run 10000  # starts at step 125

then a compute called back to by python/invoke on step 200 will not have its eflag/vflag timestep trigger set.
b/c FixPyInvoke::post_force() wlll not have been called on step 100.

The solution is to do like fix ave/time does and add an init() function to FixPyInvoke which makes a call to addstep_compute_all(nextvalid()).  This will be called on step 125 and set the trigger for step 200.
For the added init() code, you should also add a comment like the one in FixAveTime::init() to clarify why this is being done.

On a related note, the fix python/invoke doc page does not have this section: 
Restart, fix_modify, output, run start/stop, minimize info
which all fixes should typically have.

In this case, its content should be the exact same text as the fix nve doc page.
Which would explain (relevant to this issue) that fix python/invoke is not invoked during energy minimization.

Steve

2025-01-28 18:40 UTC, akohlmey commented
@rbberger please assign the pull request to me, when Steve's concerns are addressed and I will merge it.

2025-01-30 07:10 UTC, rbberger commented on src/PYTHON/fix_python_invoke.cpp
> +  modify->clearstep_compute();
Added comments.

2025-01-30 07:11 UTC, rbberger commented
@sjplimp made the suggested changes.

2025-01-30 15:27 UTC, sjplimp approved these changes
thanks

2025-01-30 19:21 UTC, merged