Kokkos versions of bispectrum and Gaussian descriptors on grid
lammps/lammps pull request #4401
Opened 2024-12-05 16:13 UTC by RandomDefaultUser

**Summary**

A while back @athomps implemented the calculation of bispectrum descriptors, based on the SNAP formalism, into LAMMPS. This was done as part of the MALA machine learning workflow (results have been published in a few papers already, for a good see, e.g., https://arxiv.org/abs/2411.19617). This PR introduces a Kokkos version of the bispectrum descriptor calculation on the grid. It further introduces the calculation of Gaussian descriptors (Gaussian functions centered on atoms, calculated per grid point), for which also a Kokkos version exists. These Gaussian descriptors are needed within MALA to efficiently evaluate the structure factor. With Kokkos, both calculations can be done with multiple GPUs, which is crucial for the MALA workflow .

**Related Issue(s)**

None. This implementation has closed multiple within https://github.com/mala-project/mala though. 

**Author(s)**

Andrew Rohskopf @rohskopf (at the time of implementation, Sandia National Labs)
Lenz Fiedler @RandomDefaultUser (me, currently at Helmholtz-Zentrum Dresden Rossendorf, Germany)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This PR is backwards compatible.

**Implementation Notes**

Verifying the correctness of results with just LAMMPS. The correctness of the results has been extensively studied with MALA though, the results can be found in https://arxiv.org/abs/2411.19617 and https://nbn-resolving.org/urn:nbn:de:bsz:14-qucosa2-936753. I can provide (closed) PRs from the MALA project as well if that helps. 

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

2024-12-05 16:17 UTC, RandomDefaultUser commented
I see that there are some tests failing, I was not aware that there would be issues. Good thing I put the PR as draft, I will fix that before marking it ready for review.

2024-12-06 17:15 UTC, athomps commented
Formatting issues are fixed. All checks have passed. So I have switched this to ready for review.

2024-12-06 17:21 UTC, athomps reviewed
This looks very solid. However, the doc pages will need to be updated.  In partcular, a new doc page for the Gaussian descriptor needs to be created at doc/src/compute_gaussian_grid(_local).rst. I suggest stripping down and editing doc/src/compute_sna_atom.rst.

2024-12-09 13:05 UTC, RandomDefaultUser commented
Ah you are right @athomps, forgot about the docs. I added them now, let me know if there is anything missing.

2024-12-19 09:07 UTC, RandomDefaultUser commented
@athomps I added your commit as discussed!

2024-12-19 15:09 UTC, athomps reviewed
I approve

2024-12-19 15:10 UTC, athomps approved these changes

2024-12-19 16:23 UTC, RandomDefaultUser commented
There were two minor style issues in the commit updating the docs, I fixed them, we should be got to go now.

2024-12-24 01:33 UTC, akohlmey commented
There is a problem compiling with some platforms.

2024-12-24 17:40 UTC, stanmoore1 commented
>There is a problem compiling with some platforms.

@akohlmey yes, this came from merging https://github.com/lammps/lammps/pull/4391. @weinbe2 and I will work on this after the break.

2025-01-10 01:02 UTC, akohlmey commented
> > There is a problem compiling with some platforms.
> 
> @akohlmey yes, this came from merging #4391. @weinbe2 and I will work on this after the break.

@stanmoore1 Just a gentle reminder that this is still pending.

2025-01-14 23:10 UTC, stanmoore1 commented
@RandomDefaultUser thank you for this contribution. I fixed the compile errors from merging https://github.com/lammps/lammps/pull/4391 in my branch here: https://github.com/stanmoore1/lammps/tree/mala. I don't have permission to push to your branch, and couldn't seem to create a PR either. Can you please merge my changes into your branch?

@weinbe2 FYI

2025-01-14 23:54 UTC, stanmoore1 commented
@RandomDefaultUser actually Axel showed me how to submit a PR to your fork, see https://github.com/mala-project/lammps/pull/6.

2025-01-15 09:46 UTC, RandomDefaultUser commented
Hi @stanmoore1 thank you so much for fixing the compile issues! I will merge the PR you created right away so that we can then hopefully merge this one as well!

2025-01-16 16:05 UTC, athomps approved these changes
I approve.

2025-01-20 22:26 UTC, stanmoore1 requested changes
@RandomDefaultUser Thank you again for this contribution. Overall the code looks good. My only request is to remove the unneeded commented out parts of the code so it is a little cleaner and easier to read. A few comments are fine but please remove large blocks of unused code. Thanks!

2025-01-20 22:26 UTC, stanmoore1 commented on src/KOKKOS/compute_sna_grid_local_kokkos.cpp
> +// The following chunk will compile but we're gonna try a wrapper approach like pair snap.
Please remove extra comments.

2025-01-20 22:26 UTC, stanmoore1 commented on src/KOKKOS/compute_sna_grid_kokkos_impl.h
> +    printf("We are triclinic %f %f %f\n", xtmp, ytmp, ztmp);
For example: remove debug comments here.

2025-01-21 16:11 UTC, RandomDefaultUser commented
Hi @stanmoore1 , thanks for the feedback, you're right, there were some leftovers from debugging in the code. I removed them, let me know if there are still comments you think are unnecessary and should maybe be removed.

2025-01-21 16:53 UTC, athomps commented
This is ready to go, I think! @stanmoore1 do you have any concerns?

2025-01-22 00:05 UTC, stanmoore1 requested changes
@RandomDefaultUser I missed a file in `/src/KOKKOS/Install.sh`, can you please add that? I had a few other minor change requests too, otherwise this is ready to merge.

2025-01-22 00:05 UTC, stanmoore1 commented on src/KOKKOS/Install.sh
> +action compute_sna_grid_local_kokkos_impl.h compute_sna_grid_local.cpp
Need to add the `compute_gaussian_grid_local_kokkos.*` files too here.

2025-01-22 00:05 UTC, stanmoore1 commented on src/KOKKOS/compute_sna_grid_kokkos_impl.h
> +   Contributing authors: Christian Trott (SNL), Stan Moore (SNL),
@RandomDefaultUser Please feel free to remove our names and add yours since you created this file.

2025-01-22 00:05 UTC, stanmoore1 commented on src/KOKKOS/pair_mliap_kokkos.cpp
> +  //printf(">>> ntypes: %d\n", atom->ntypes);
This needs to be removed or guarded so only one rank prints it out and printed to both screen and logfile as done in other places.

2025-01-22 07:14 UTC, RandomDefaultUser commented on src/KOKKOS/Install.sh
> +action compute_sna_grid_local_kokkos_impl.h compute_sna_grid_local.cpp
Got it, I have added the files!

2025-01-22 07:16 UTC, RandomDefaultUser commented on src/KOKKOS/compute_sna_grid_kokkos_impl.h
> +   Contributing authors: Christian Trott (SNL), Stan Moore (SNL),
I credited @rohskopf because he created the file, I am only taking care of the PR. But thanks for pointing this out!

2025-01-22 07:17 UTC, RandomDefaultUser commented on src/KOKKOS/pair_mliap_kokkos.cpp
> +  //printf(">>> ntypes: %d\n", atom->ntypes);
Got it, I removed it!

2025-01-22 07:18 UTC, RandomDefaultUser commented
I addressed the small change requests you had @stanmoore1, let me know if there is anything else!

2025-01-22 21:47 UTC, stanmoore1 commented
Doing a quick test on GPU now.

2025-01-22 22:38 UTC, stanmoore1 commented
GPU tests look fine, but I found a couple more issues with the GNU Make build. @RandomDefaultUser can you merge my PR here: https://github.com/mala-project/lammps/pull/7? Thanks.

2025-01-23 08:43 UTC, RandomDefaultUser commented
Of course, I just merged the PR!

2025-01-23 16:46 UTC, stanmoore1 approved these changes

2025-01-23 16:47 UTC, stanmoore1 commented
This PR is ready to merge from my POV.

2025-01-23 17:06 UTC, merged