add area and volume preserving barostats
lammps/lammps pull request #4419
Opened 2024-12-19 03:57 UTC by srtee

**Summary**

Allows barostats to preserve volume or area through deviatoric barostatting (setting suitable hydrostatic stress trace to zero).

**Author(s)**

Shern Tee (Griffith University), s.tee@griffith.edu.au / shernren@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Only new input options -- should not modify existing behaviour.

**Implementation Notes**

Added `vol_preserve_flag` and `area_preserve_flag` to `FixNH` (!!), and offsets `omega_dot` vectors as needed during `nh_omega_dot()` so that the necessary sums are zero (thus preserving volume or area as needed).

Technically either option removes one barostat DOF. Anybody who cares enough will be able to modify DOF as needed (I'm not sure even existing `iso` / `aniso` / `tri` options track their DOFs to similar accuracy ...).

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

Follows from MatSci discussion: https://matsci.org/t/molecular-dynamics-simulation-in-the-n-v-a-0-t-ensemble/59675/4

2024-12-19 11:12 UTC, akohlmey commented on doc/src/fix_nh.rst
> +.. versionadded:: latest
```suggestion
.. versionadded:: TBD
```

2024-12-19 11:14 UTC, akohlmey commented on src/fix_nh.cpp
> +      error->warning(FLERR,"Fix {} has x and y pressures that do not sum to zero but is preserving xy area", style);
```suggestion
      if (comm->me == 0)
        error->warning(FLERR,"Fix {} has x and y pressures that do not sum to zero but is preserving xy area", style);
```

2024-12-19 11:19 UTC, akohlmey requested changes
These changes need to be confirmed with all classes that derive from FixNH
```
$ grep -l public.FixNH.\{ *.h */*.h
fix_nh_sphere.h
fix_nph.h
fix_npt.h
fix_nvt.h
fix_nvt_sllod.h
ASPHERE/fix_nh_asphere.h
BODY/fix_nh_body.h
EFF/fix_nh_eff.h
GPU/fix_nh_gpu.h
INTEL/fix_nh_intel.h
KOKKOS/fix_nh_kokkos.h
OPENMP/fix_nh_omp.h
SHOCK/fix_nphug.h
UEF/fix_nh_uef.h
```
and it is going to be best to add corresponding tests to `unittest/force-styles/tests`

2024-12-19 19:29 UTC, jtclemm commented
Not sure how important uniform notation is, but the functionality of _preserve xyz_ would be enabled in fix deform using _box volume_. But the _box_ argument is also designed to provide additional functionality, so not exactly one-to-one.

2025-01-23 22:55 UTC, athomps commented
I have not looked at this in detail.  The functionality is useful and the core code looks good. My only immediate concern is the restriction: `all pressures sum to zero to preserve xyz volume`.  By fixing the volume, the resultant average pressure from the simulation will also be fixed to some value, but that value will not be zero. Maybe a better restriction would be `all target axial stresses must be equal and all target shear stresses must be zero` i.e. zero deviatoric stress.

2025-01-25 00:19 UTC, athomps commented
I agree with @jtclemm that this is similar to the `volume` keyword in `fix deform`. It also has something in common with the existing `couple` keyword in `FixNH`.  Combining these two ideas, I think it would not be hard to convert this to a simple and general optional keyword `volume` or `anticouple`, similar to `couple`:

`volume value = none or xyz or xy or yz or xz`

In the code, this would have the effect of offsetting `omega_dot` for the anti-coupled dimensions so that they sum to zero. At each timestep, the corresponding scale factors applied to the anti-coupled dimensions will multiply to 1, so area or volume is preserved.  I also see no need to check the values of the target stress values. Users should be free to (ab)use this as they like.  The only checks that are strictly needed are the same as the dozen or so checks for the `couple` keyword.

2025-06-10 21:47 UTC, akohlmey commented
@srtee This has not seen any activity for two months. Are you still planning to work on it?
Ahead of the stable release we are trying to pare down the pull request list to those under active development to ideally keep the list of pending pull requests down to just one page (everything on the second page and beyond gets rarely looked at).

One way to move forward could be to close this pull request and either resubmit it later when you have time, or submit a feature request issue that then points to the closed pull request as a starting point for somebody to take over and flag it as "volunteer needed".

2025-06-12 11:46 UTC, srtee commented
I'm not planning to work actively on this. Let's just close the PR for now -- if someone else has a feature request mentioning this, we can reopen it then.

2025-06-12 15:34 UTC, akohlmey commented
This was converted into issue #4623

2025-06-12 15:34 UTC, closed without merging